In [1]:
import glob
import pandas as pd

In [24]:
data = pd.read_csv("Demonatization_tweets.csv", encoding='latin-1')

In [25]:
data["text"][8]

'RT @sumitbhati2002: Many opposition leaders are with @narendramodi on the #Demonetization \r\nAnd respect their decision,but support oppositio\x85'

# Look at the top 50 mentions in the dataset (mentions in this dataset refers to the @s)

In [31]:
import re
import pandas as pd
from collections import Counter
mention_list = []
def top_50_mention(text):
    pattern = r'(?<!\w)@s\w+'
    words_starting_with_at = re.findall(pattern, text)
    mention_list.extend(words_starting_with_at)

data["text"].apply(top_50_mention)
def top_50_most_occurred_mention(word_list):
    word_counter = Counter(word_list)
    top_50_words = word_counter.most_common(50)
    return top_50_words

# Find top 50 most occurred mention
top_50_occ_men = top_50_most_occurred_mention(mention_list)

# Create DataFrame
df = pd.DataFrame(top_50_occ_men, columns=['Word', 'Count'])
print(df)

                Word  Count
0       @steve_hanke    179
1          @sanjayuv     30
2   @sardesairajdeep     29
3     @sagarikaghose     17
4         @sonunigam     16
5      @saaxenanurag     15
6        @s_cartoons     14
7         @s_navroop     13
8   @sandipsabharwal     12
9     @sajid_Yousuf_     11
10     @sambitswaraj     11
11  @sumitkashyapjha     11
12            @sri50     11
13     @sitaramlamba     10
14     @sudarsansand     10
15          @smarket     10
16    @sureshpprabhu      9
17         @sunetrac      9
18     @sanjayuvacha      9
19       @suryanavin      8
20     @sukanyaiyer2      8
21     @sampadscales      8
22            @sffed      7
23  @sunilsharma_jmu      7
24    @satishacharya      6
25   @sundeepgummadi      6
26     @sardanarohit      5
27    @shashidigital      5
28   @salonishuklaET      5
29      @shalinigAAP      5
30     @sumanthraman      5
31   @sanasecurities      5
32    @satishkumarm2      5
33          @su_nils      5
34   @srinivasanravi      5
35           @shamee      4
36     @shripadynaik      4
37         @snapchat      4
38         @sona2905      3
39            @sidin      3
40     @surjitbhalla      3
41     @shekhar_ojha      3
42        @soumikdas      3
43        @spati2012      3
44     @shilpakannan      3
45   @sangwan_sujata      3
46      @satish_char      3
47     @sooryajith12      3
48      @smritiirani      3
49      @snehabanerg      3

# Find the top 50 most frequently used hashtags (#)

In [32]:
import re
import pandas as pd
from collections import Counter
mention_list = []
def top_50_mention(text):
    pattern = r'(?<!\w)#\w+'
    words_starting_with_at = re.findall(pattern, text)
    mention_list.extend(words_starting_with_at)

data["text"].apply(top_50_mention)
def top_50_most_occurred_hashtag(word_list):
    word_counter = Counter(word_list)
    top_50_words = word_counter.most_common(50)
    return top_50_words

# Find top 50 most occurred mention
top_50_occ_hastag = top_50_most_occurred_hashtag(mention_list)

# Create DataFrame
df = pd.DataFrame(top_50_occ_hastag, columns=['hashtag', 'Count'])
print(df)

                   hashtag  Count
0          #Demonetization   3884
1          #demonetization   3783
2          #DeMonetization    918
3                   #India    356
4             #nitishkumar    257
5                    #demo    174
6                   #GLvMI    145
7     #CorruptionFreeIndia    103
8              #BlackMoney     94
9                    #Modi     92
10            #VijayMallya     86
11  #IndiaFightsCorruption     79
12         #DEMONETIZATION     60
13                    #BJP     56
14            #NoMoneyYaar     53
15            #Demonetizat     47
16              #SonuNigam     47
17              #RatanTata     44
18         #DeMonetisation     44
19               #Insights     44
20               #bulletin     44
21        #boycottsnapchat     44
22                    #RBI     42
23           #NarendraModi     41
24          #LifeInsurance     34
25         #demonetisation     31
26          #YouTubeIsDead     30
27                  #NMApp     29
28      #MeraDeshBadalRaha     28
29                 #PMModi     26
30                   #news     25
31               #TrustBJP     25
32                #Bypolls     24
33                    #not     23
34                #YouTube     23
35               #CGDTalks     23
36             #IndiaKaDil     22
37                  #india     22
38              #Hilarious     21
39             #blackmoney     20
40                 #Hitler     20
41              #WarOnCash     20
42              #lifehacks     19
43               #Doltiwal     18
44       #JaiChandKejriwal     18
45                 #survey     18
46                     #PM     18
47                  #Delhi     18
48              #NorthEast     18
49                #ITVideo     18

# Rule 1 - Extracting the sentences with President's mention

In [33]:
# importing spacy and its matcher function
import spacy
from spacy.matcher import Matcher

# load english language model
nlp = spacy.load('en_core_web_sm',disable=['ner','textcat'])

In [89]:
# function to find sentences mentioning president
def find_names(text):

    names = []

    # spacy doc
    doc = nlp(text)

    # pattern
    pattern = [{'LOWER':'prime'},
              {'LOWER':'minister'},
              {'POS':'ADP','OP':'?'},
              {'POS':'PROPN'}]

    # Matcher class object
    matcher = Matcher(nlp.vocab)
    matcher.add("names",[pattern])

    matches = matcher(doc)

    # finding patterns in the text
    for i in range(0,len(matches)):

        # match: id, start, end
        token = doc[matches[i][1]:matches[i][2]]
        # append token to list
        names.append(str(token))

    return names

In [90]:
# extracting sentences with prime minister mentions
extracted_sentences = []
for i in range(data.shape[0]):
    extracted_sentences.append(find_names(data['text'][i]))

# # storing the extracted sentences in the dataframe
data['Prime minister'] = extracted_sentences

In [91]:
data

,Unnamed: 0,text,President_Names,Prime minister
0,1,RT @rssurjewala: Critical question: Was PayTM ...,[],[]
1,2,RT @Hemant_80: Did you vote on #Demonetization...,[],[]
2,3,"RT @roshankar: Former FinSec, RBI Dy Governor,...",[],[]
3,4,RT @ANI_news: Gurugram (Haryana): Post office ...,[],[]
4,5,RT @satishacharya: Reddy Wedding! @mail_today ...,[],[]
...,...,...,...,...
14935,14936,RT @saxenavishakha: Ghost of demonetization re...,[],[]
14936,14937,N d modi fans-d true nationalists of the count...,[],[]
14937,14938,RT @bharat_builder: Lol. Demonetization has fi...,[],[]
14938,14939,RT @Stupidosaur: @Vidyut B team of BJP. CIA ba...,[],[]
14939,14940,"@Vidyut B team of BJP. CIA baby. CCTV, EVM but...",[],[]

In [92]:
for val in data['text'].tolist():
    print(val)

RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @ANI_news: Gurugram (Haryana): Post office employees provide cash exchange to patients in hospitals #demonetization https://t.co/uGMxUP9
RT @satishacharya: Reddy Wedding! @mail_today cartoon #demonetization #ReddyWedding https://t.co/u7gLNrq31F
@DerekScissors1: Indias #demonetization: #Blackmoney a symptom, not the disease https://t.co/HSl6Ihj0Qe via @ambazaarmag
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @sumitbhati2002: Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support oppositio
National reform now destroyed even the essence of sagan. Such instances urge giving #demonetization a second though https://t.co/eyySIREiUq
Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support opposition just b'coz of party
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
@Jaggesh2 Bharat band on 28??<ed><U+00A0><U+00BD><ed><U+00B8><U+0082>Those who  are protesting #demonetization  are all different party leaders.
RT @Atheist_Krishna: The effect of #Demonetization !!
. https://t.co/A8of7zh2f5
RT @sona2905: When I explained #Demonetization to myself and tried to put it down in my words which are not laced with any heavy technical
RT @Dipankar_cpiml: The Modi app on #DeMonetization proves once again that the govt is totally indifferent to the mounting misery and hards
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
RT @pGurus1: #Demonetization The co-operative banking sector in Kerala is as good as a tax haven. Is Kerala a Black Money HQ? https://t.co/
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
RT @MahikaInfra: @narendramodi
@Swamy39
The success of #Demonetization will depend on how swiftly govt replenish the currency

Pls avoid Ba
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @AAPVind: #Demonetization Is Disaster!  @naam_pk
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @Gadgets360: After the #demonetization, searches about #NarendraModi's app are trending on app stores https://t.co/ZetKRqqClX
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
RT @mayankjain100: #demonetization is Communal and Black Money is Secular...
LOL. #Demonetization Effect. https://t.co/aA5lfy9ALG
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact o https://t.co/TPYJgXFBY8
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
@arunjaitley @narendramodi Lrnd frm a frnd-Banks r asking employees to comeback 2sales &amp; BAU Operations #Demonetization
RT @kanimozhi: Ts is exactly what Pappu &amp; opposition has done to themselves by opposing #Demonetization Now none can stop Modi bandwagon ti
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
@dineshgrao you have 12.5 k followers yet you are not getting enough likes for your tweets against #demonetization. You need to introspect.
#DeMonetization Effect : Visa, Master Card, Amex all Accepted :) https://t.co/ozDwcPKjaI
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
RT @harshkkapoor: #DeMonetization survey results after 24 hours
5Lacs opinions
Amazing response&amp; Commitment in fight against Blackmoney
@na
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @rohanmlw: #demonetization eye opener video bt i doubt as few jurnos don't want2 hear +ve of @narendramodi @sardesairajdeep @ravishndtv
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha
RT @nmleo1: Is #ModiSarkar 's #achedin campaign on #demonetization a #goebbelsian #masterstroke that turns blind eye to #GroundZero shocks?
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
#demonetization is Communal and Black Money is Secular...
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @nmleo1: @MinhazMerchant #demonetization hardly affects tax dodgers &amp; #NETAS who excel in #CashlessCorruption &amp; have multiplied bad weal
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
Section 144 issued by District Magistrate, #Indore prohibiting #socialmedia posts on #demonetization, Why??
#citizen https://t.co/5Tn7aNBTsi
RT @pGurus1: CPI-M opposes Co-op Banks in West Bengal but supports them in Kerala! Y Pawar U-turned on #Demonetization https://t.co/ThzaV7r
RT roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact o https://t.co/vCWWjxu0wb
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @pGurus1: #Demonetization move of Modi; Who is supporting it, who is opposing it and why? A complete coverage of all parties - https://t
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
Effects of sluggish economy, negative IIP, #Demonetization ! Does the Great Leader even bother except continued dra https://t.co/DuvbMtEi1Y
RT @kanimozhi: Ts is exactly what Pappu &amp; opposition has done to themselves by opposing #Demonetization Now none can stop Modi bandwagon ti
RT roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact o https://t.co/5J6jZXbY81
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
RT @bhaiyyajispeaks: Here @sardesairajdeep struggling for one answer against #Demonetization, He should have taken some Congress leader lik
#Demonetization and the Indian Economy An Interview by Doordarshan with Sri S.Gurumurthy https://t.co/LdeBCADAeR
RT @Gadgets360: After the #demonetization, searches about #NarendraModi's app are trending on app stores https://t.co/ZetKRqqClX
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha
RT @NilimDutta: After much contemplation I have come to the conclusion that nothing explains Modi's #DeMonetization better than monumental
RT @Currency_crisis: What #demonetization indicates is loss of freedom
Besides laws/constitution/court/cops 2 govern people
govt is using m
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
Ppl of India extending overwhelming supprt to @narendramodi Ji's crusade agnst black money.Survey @timesofindia https://t.co/Axqd8FOwpK
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @harshkkapoor: #DeMonetization survey results after 24 hours
5Lacs opinions
Amazing response&amp; Commitment in fight against Blackmoney
@na
People from rural areas are coming to Delhi just to withdraw cash.

They have given up on govt. logistics.

@ravishndtv #Demonetization
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact o https://t.co/vv9qtRqqSI
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @NilimDutta: After much contemplation I have come to the conclusion that nothing explains Modi's #DeMonetization better than monumental
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
#demonetization 90 % of population is accepting it as country building measure, why these so called politicians opp https://t.co/f91j6tZjZ2
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
15 days after #demonetization, country is still suffering 4m acute shortage of currency notes.
Big loss 2 economy
Share market tumbling
SOS
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @TheOfficialSBI: As of today, 33000 thousand ATMs are functioning. - SBI Chairman, Smt. Arundhati Bhattacharya. #Demonetization
RT @ashu3page: A man shaved his head at Jantar-Mantar in protest against #Demonetization  on 13th day of the move. https://t.co/IeXuia3J0X
Very unfortunate... India slips due to #demonetization
@BJP4India @PMOIndia @RanaAyyub @TruthOfGujarat @AnupamPkher
https://t.co/6QhcGyBpKw
What #demonetization indicates is loss of freedom
Besides laws/constitution/court/cops 2 govern people
govt is using money 2 control people
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @sitaramlamba: Cooperative banks shut down, sowing season completely disrupted, agri markets &amp; Farmers badly affected #demonetization
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha
RT @embracetheart: Delete! Pathetic PM who conducts false poll and self praises himself. #demonetization #BogusPoll #ModiScaredOfParliament
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
#Demonetization
https://t.co/0kq8BsJ1iS
When PM is in, opposition is out of parliament.
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @CMOMaharashtra: Watch what @sonunigam thinks about #demonetization .. https://t.co/vXt09c64zY
RT @ShashiTharoor: . @anandkamal Frankly i don't understand why @narendramodi doesn't address Parlmnt on #Demonetization. It's his duty&amp;wil
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
RT @kanimozhi: Ts is exactly what Pappu &amp; opposition has done to themselves by opposing #Demonetization Now none can stop Modi bandwagon ti
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
RT @kapil_kausik: #Doltiwal I mean #JaiChandKejriwal is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo
RT @_avenu: Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMu
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
RT @pGurus1: #Demonetization move of Modi; Who is supporting it, who is opposing it and why? A complete coverage of all parties - https://t
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
Aam aadmi punished for sins of #blackmoney hoarders. SBI slashes  deposit rates by 1.9% #Demonetization #netascashin https://t.co/rqjsdiGvcG
Teacher: is there anybody who is absent today?
(No response )
Teacher says 100% attendance
#Demonetization #App #survey
@DonMufflerMan <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0080><ed><U+00A0><U+00BD><ed><U+00B8><U+00A0><ed><U+00A0><U+00BD><ed><U+00B8><U+00AE>
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha
RT @ANI_news: The queues are not getting longer but are getting shorter day by day: Chanda Kochar,ICIC MD and CEO #demonetization https://t
RT @DrGPradhan: 8

This tweet of @minimathur BIBI explains why she is having a prob with #demonetization ..In first part she says she can't
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @PIB_India: Watch briefing on #Demonetization by DEA Secy @DasShaktikanta this morning here:
https://t.co/TDj2A6uO5u
@DeshhBhakt seems deskbhakt was in hibernation mode when GPS enabled 2000 rs was launched by #Modo 4 #demonetization <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082>@MonaAmbegaonkar
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
RT @dhrumilpatel: Looks Ambit Capital, literally Choked with #demonetization, come-on U can't lower d GDP nos by huge margin.
Perhaps, they
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
RT @bi_india: .@airtelindia takes a bite of the governemnt big #demonetization pie, becomes first #paymentbank to go live

https://t.co/gZv
RT @harshkkapoor: #DeMonetization survey results after 24 hours
5Lacs opinions
Amazing response&amp; Commitment in fight against Blackmoney
@na
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
The opposition is getting troubled because all their #BlackMoney have become just a piece of paper due to #demonetization #<U+092C><U+0940><U+092E><U+093E><U+0930>_<U+0935><U+093F><U+092A><U+0915><U+094D><U+0937>
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @roshankar: Harvard's Larry Summers calls #Demonetization as poor policy with disproportionate negative impact on poor/trade.

https://t
RT @ZeeNewsSports: #Demonetization: @harbhajan_singh gives hilarious 'shagun' suggestion to those struggling with wedding season

https://t
@sritara @GabbbarSingh @sidin
Please read alternative side of story also on #Demonetization &amp; support to PM Modi
https://t.co/SLJoymBy1m

All Etv Hindi Channels. https://t.co/umYsLI7Yhl
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @rssurjewala: Modiji's #Demonetization. Farmers in acute distress-No buyer for produce &amp; no money for Rabi sowing.Anyone listening? http
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @kavita_krishnan: Sanghi DMs ban social media criticism of #demonetization. Only #NMApp with scripted answers is allowed I guess :) http
@washingtonpost #trump shd learn from the stupid experiment of #demonetization done in India.. Tackles black  money, terror &amp; counterfeit.
We promise the #MinisterMenu is worth every saved 100 rupee. Don't let the #demonetization bring you down. https://t.co/hqOUgtk68V
RT @kanimozhi: Why @ArvindKejriwal &amp; @MamataOfficial trying to instigate Indians 4 a Civil war in India against #demonetization Arrest them
RT @dna: Tweet to @dna #DNARumourBuster with any questions you may have about #demonetization and we'll give you the real news.
#KnowMore h
@NewsX @PMOIndia @BJP4India Don't portray wrong pic @JhaSanjay ji.  Pl support #demonetization. It's good for poor.The student was Vcoward
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
Over 90% of respondents feel govt's move to tackle #black money is above four-star rating. #demonetization #survey via TOI @narendramodi
@PTI_News Why oppns r running from pillar to post against #demonetization.It beyond imanization. Now NOTEBADI SE BHARATBANDI TAK.
RT @kanimozhi: Thanks to #demonetization 75% reduction in crime rate in India. Black money seems to be the sole reason 4 all problems in In
RT @hemster: Aam Aadmi supports #Demonetization
And supports @narendramodi https://t.co/uq9gOigp3S
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @kanimozhi: Why @ArvindKejriwal &amp; @MamataOfficial trying to instigate Indians 4 a Civil war in India against #demonetization Arrest them
RT @kanimozhi: Why @ArvindKejriwal &amp; @MamataOfficial trying to instigate Indians 4 a Civil war in India against #demonetization Arrest them
https://t.co/w4R04t0ir3 shame on @CMofKarnataka @parameshwar
#Demonetization
Live updates: Modi's App survey result shows over 93% people support #demonetization move https://t.co/Ngf6j55rqf
RT @kanimozhi: Thanks to #demonetization 75% reduction in crime rate in India. Black money seems to be the sole reason 4 all problems in In
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @kanimozhi: Why @ArvindKejriwal &amp; @MamataOfficial trying to instigate Indians 4 a Civil war in India against #demonetization Arrest them
RT @SV99999: #Demonetization

9 New Steps to Help Citizens Fight the Cash Crunch

https://t.co/HFrbK2Lim9
RT @iarunmani: Left is going to file a petition in SC against govts decision on #demonetization . My que is why the hell don't you debate i
RT @kanimozhi: Thanks to #demonetization 75% reduction in crime rate in India. Black money seems to be the sole reason 4 all problems in In
RT @kanimozhi: Thanks to #demonetization 75% reduction in crime rate in India. Black money seems to be the sole reason 4 all problems in In
RT @kanimozhi: Why @ArvindKejriwal &amp; @MamataOfficial trying to instigate Indians 4 a Civil war in India against #demonetization Arrest them
#Demonetization

9 New Steps to Help Citizens Fight the Cash Crunch

https://t.co/HFrbK2Lim9
RT @arifkhan7: Bangalore's @tinucherian visits 23 ATMs to see if media is lying about the note ban? #demonetization https://t.co/0Gmlpksrpx
I'm struggling with no cash i have to pay for the hotel in cash and they don't accept dollars @narendramodi #Demonetization #india #tourist
Aam Aadmi supports #Demonetization
And supports @narendramodi https://t.co/uq9gOigp3S
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
@quizderek  sir, u r a respectd prsn, but wid ths move against #demonetization pepl r qustning ur intntn!hope u r nt involved in sarda scam
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
India has spoken again..@AamAadmiParty @INCIndia @AITCofficial how many times will u learn a lesson? https://t.co/Em9hsb4wCH
Lower interest rate will ultimately lead to more buyers because of #LowerEMI. #HappyHomes #Demonetization https://t.co/A6LmfiVsXB
#DeMonetization PMModi had exposed TMC &amp; it's Chief Mamta Di with reg corruption in WB, that Bengal Didn't change b https://t.co/BL4HCG0GVS
RT @IRS_India: So are you in support of the #demonetization or not?
Well, according to public opinion majority of the Indians sure are!
#Ma
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @jairajp: So this #DeMonetization has been so Tragic in Implementation that modi govt is Flouting RBI rules for Banking License and Oper
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
RT @iarunmani: Left is going to file a petition in SC against govts decision on #demonetization . My que is why the hell don't you debate i
RT @jairajp: One cartoon that explains everything thats happening in #DeMonetization Missed Target; Bad Execution; Severe Collateral Dama
RT @bishnoikuldeep: Govt hasn't exempted essential items like food, milk, public transport but exempted petrol&amp;flights from #demonetization
From #MannKiBaat to #JanKiBaat on #demonetization.
#Citizens on #DEMONETIZATION #janjankibaat @narendramodi https://t.co/5Rgxh7EAB6
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @IndiaFactsOrg: #Demonetization: The Ultimate Weapon against Black economy https://t.co/fWvEuH2De6 via @IndiaFactsOrg
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
#Demonetization @RBI  @narendramodi Bank officials can make monetization a failure. Stop the fraud and corruption going on in banks.
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @IndiaFactsOrg: #Demonetization: The Ultimate Weapon against Black economy https://t.co/fWvEuH2De6 via @IndiaFactsOrg
@narendramodi @AmitShah Akali Dal is joining opposition party against #Demonetization but BJP is continuing with there coalition government.
Is that why someone from there is among the most vocal opponents of #Demonetization ? <ed><U+00A0><U+00BD><ed><U+00B8><U+0089> No wonder ! https://t.co/iUlZvzbJ5s
RT @JaiPoswal1995: 92% people support @narendramodi's #Demonetization on #Modi App &amp; insist decision should not be back
https://t.co/2lelg
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
RT @JaiPoswal1995: 92% people support @narendramodi's #Demonetization on #Modi App &amp; insist decision should not be back
https://t.co/2lelg
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
#SC issued notice on transfer and stay petitions filed by centre to transfer all matters relating to #demonetization to one court. No Stay.
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
93% support govt on #demonetization move. Parties, pls take note. Your voters support this move. At least now, conduct parliament business
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
Indian PM @narendramodi lambasted critics of the #demonetization drive by saying they want #corruption #Bribery to continue. A great leader!
RT @coomarashish: C-Voter on #Demonetization:
Only 22% happy with implementation, when asked to mark the same, 66% says 'Good'.
@manakgupta
@awasthis @5pm @News18India #Demonetization The way they are creating scenario/ Now BharatBandh this shall reduce image of opposition
RT @dna: Watch: Somebody made a spoof video on #demonetization with #AeDilHaiMushkil trailer and it's hilarious https://t.co/yqe4ZrMEMz htt
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @yugaparivartan: Irony of our times. Jholachap economists who like giving 100Rs in NREGA opposing #Demonetization, while the free-market
@awasthis @5pm @News18India #Demonetization : Opposition should go to  constituencies  help people have patience so it improves their image.
RT @ANI_news: The queues are not getting longer but are getting shorter day by day: Chanda Kochar,ICIC MD and CEO #demonetization https://t
Left is going to file a petition in SC against govts decision on #demonetization . My que is why the hell don't you debate in parliament?
RT @DrShobha: #Demonetization  taught me minimalism .

Less stuff ! More happiness !

Thank you Prime Minister @PMOIndia

#Insights
From #MannKiBaat to #JanKiBaat on #demonetization.
#Citizens on #DEMONETIZATION #janjankibaat @narendramodi https://t.co/HbOZ0wN7cP
RT @jankibaat1: From #MannKiBaat to #JanKiBaat on #demonetization.
#Citizens on #DEMONETIZATION #janjankibaat @narendramodi @PMOIndia #nam
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @IndiaFirst_2019: Have You Shared Your Views on #Demonetization to #PMModi Take Part in Survey on #NMApp  &amp; Be A Part of Nation Building
EXCLUSIVE: Inside vijayshekhar's Paytm, the first 24 hours after #demonetization

https://t.co/IdMgdpx0sz
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
Irony of our times. Jholachap economists who like giving 100Rs in NREGA opposing #Demonetization, while the free-marketists applauding!
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @YSRCParty: Days before #Demonetization announcement, @ncbn sold his Heritage shares,clearly evident that he had prior knowledge of the
They are all protesting against #Demonetization But how many of them have been so vocal about Corruption? Deliberat https://t.co/N2HX5UQW0r
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ShashiTharoor: Joined the line of Opposition MPs demonstrating solidarity on #demonetization &amp;demanding that @PMOIndia address Parliame
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
#ndtv cooperate with the govt their decision of #demonetization is correct... Pls spread positive news about it...#jaihind
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
How many parties opposing #demonetization on d basis of inconvenience 2 poor has on record helped poor 2 come out of prob?@MamataOfficial
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @kanimozhi: Everyone seems to hate the rich, even the rich hates richer and the richer hates the richest. #Demonetization.
RT @nipfp_org_in: Read latest NIPFP blogpost titled "#Demonetization: Cure and Care", by Dr. Pinaki Chakraborty.
@pinakicha
https://t.co/L
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
RT @ShefVaidya: #DeMonetization is certainly hurting Lord @ArvindKejriwal, Behen Bagwati, @OfficeOfRG and @MamtaOfficiaI a LOT! https://t.c
RT @sudarsansand: My humble appeal to all to pl have patience and draw what they need from ATMs during this #Demonetization phase. My SandA
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
From #MannKiBaat to #JanKiBaat on #demonetization.
#Citizens on #DEMONETIZATION #janjankibaat @narendramodi https://t.co/MYD5ogLY4X
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @airnewsalerts: Samajwadi Party's Jaya Bachchan and AAP join TMC protest against  #demonetization at Jantar Mantar. https://t.co/U8g4C7H
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @bi_india: EXCLUSIVE: Inside @vijayshekhar's @Paytm, the first 24 hours after #demonetization

https://t.co/2uJCMujeO8
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
@Manjunaath people who think that #BJP will pay for the #demonetization are shortsighted
EXCLUSIVE: Inside @vijayshekhar's @Paytm, the first 24 hours after #demonetization

https://t.co/2uJCMujeO8
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
RT @sudarsansand: My humble appeal to all to pl have patience and draw what they need from ATMs during this #Demonetization phase. My SandA
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @saaxenanurag: 700 Crores rupees of cash found in 3 medical colleges. Clearing the massive rot in medical admissions.

#Demonetization
@maitreesh on #demonetization "ironically, this reform may even increase the stock of black money"...https://t.co/gHdkL2epAT @roadscholarz
RT @PtAmitSharma: 700 Crores rupees of cash found in 3 medical colleges. Clearing the massive rot in medical admissions.

#Demonetization
@suryanavin MD ItzCash , was live on ET talking about the impact of #Demonetization towards digitization in India.
https://t.co/B0rYYBkL2J
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
Currency Ban: Rs21000 Cr Deposited in Jan Dhan Yojana A/c; Max frm West Bengal. Crazy stats #DeMonetization impact.  https://t.co/uQ3BqfOAQi
86% of Indians from both rural &amp; urban areas support #demonetization, feel it was worth the inconvenience https://t.co/60BAUHAnnV #india
RT @smita_muk: BREAKING NEWS
PMapps result amnounced!
90% Indians support #demonetization
<ed><U+00A0><U+00BD><ed><U+00B1><U+008F><ed><U+00A0><U+00BD><ed><U+00B1><U+008F><ed><U+00A0><U+00BD><ed><U+00B1><U+008F><ed><U+00A0><U+00BD><ed><U+00B1><U+008F><ed><U+00A0><U+00BD><ed><U+00B1><U+008F><ed><U+00A0><U+00BD><ed><U+00B1><U+008F><U+270C><U+270C><U+270C><U+270C><U+270C><U+270C><ed><U+00A0><U+00BD><ed><U+00B1><U+0086><ed><U+00A0><U+00BD><ed><U+00B1><U+0086><ed><U+00A0><U+00BD><ed><U+00B1><U+0086><ed><U+00A0><U+00BD><ed><U+00B1><U+0086><ed><U+00A0><U+00BD><ed><U+00B1><U+0086><ed><U+00A0><U+00BD><ed><U+00B1><U+0086>
@narendramodi Zindabad!
RT @JaiPoswal1995: 92% people support @narendramodi's #Demonetization on #Modi App &amp; insist decision should not be back
https://t.co/2lelg
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas
Inside #Paytm the first 24 hours after #demonetization : https://t.co/EKWEnQFPIO #banking https://t.co/8q2dQxZiTn
Why #demonetization would not stop graft
https://t.co/y1VfBxpMgf
RT @myvotetoday: So #CJIThakur says there will be riots due to #DeMonetization Qs
.
No #SpicesNSecrets
.
No riots due to citizens #Waiting
RT @CREDAINational: Dear @PMOIndia, CREDAI supports your #Demonetization drive, &amp; we are geared up for a smoother transition towards a tran
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @myvotetoday: So #CJIThakur says there will be riots due to #DeMonetization Qs
.
No #SpicesNSecrets
.
No riots due to citizens #Waiting
RT @dnaAfterHrs: Watch: Somebody made a spoof video on #demonetization with #AeDilHaiMushkil trailer and it's hilarious https://t.co/oRYBrW
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @ModiBharosa: Huge support for PM @narendramodi s #demonetization Move Across the Nation
80-86% people back demonetization: C-voter su
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
RT @myvotetoday: 85% support #demonetization

Is this more likely now or if #SupremeCourt has another midnight hearing to stay
execution o
RT @karnataka_ioc: @indianoilcl giving cash through Mini ATMs to people in Hinterland. #IndiaKaDil. Helping rural people in #Demonetization
There is pain. There is suffering - Inflicted by #demonetization. Undoubtedly. The poorest are hit hardest - The... https://t.co/hM1bckZ9JA

there is fun living with out cash asking for help  #demonetization
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
@WeAreBBSR @deba1602 @ashishkumar_tw @kumariika Did my first transaction after #Demonetization in Noida. Driver stoood for 1 hr, me 20 mins
life of people is become so simple thanks to modi ji otherwise just to meet the targets people was forced  #demonetization
RT @MinIT_Telangana: Telangana govt's innovative solution to help farmers affected due to #Demonetization: https://t.co/NVv7slCcpr
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @airnewsalerts: . @MVenkaiahNaidu blames opposition for not allowing #Parliament to function by creating uproar over #demonetization iss
now they are going out to meet people and socializing with out any work   #demonetization
RT @ModiBharosa: #RatanTata supports PM Narendra Modi for #Demonetization https://t.co/fRTHY2Ltth
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @kavita_krishnan: Sanghi DMs ban social media criticism of #demonetization. Only #NMApp with scripted answers is allowed I guess :) http
RT @anilkohli54: corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than person
my friends are happy as they have some reason to go out and stand in que otherwise all were going out to spend  #demonetization
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @tjain2016: @narendramodi <ed><U+00A0><U+00BD><ed><U+00B9><U+008F> I'm with you,
#Demonetization was a good decision against Corruption, but why it was not planned and execut
RT @ShashiTharoor: . @anandkamal Frankly i don't understand why @narendramodi doesn't address Parlmnt on #Demonetization. It's his duty&amp;wil
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @kavita_krishnan: Sanghi DMs ban social media criticism of #demonetization. Only #NMApp with scripted answers is allowed I guess :) http
. @MVenkaiahNaidu blames opposition for not allowing #Parliament to function by creating uproar over #demonetization issue.
common man was in trouble before modi ji also so what modi ji has done for common men is not some thing new  #demonetization
RT @anilkohli54: corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than person
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @anilkohli54: Indians will condole the death political parties due to #demonetization we dont need to be in Pa we will do it openly in f
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @anilkohli54: corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than person
RT @anilkohli54: corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than person
RT @IbrahimTasleem: People around him Snatched his Mike
when Congress Leader Praising #DeMonetization in Rajasthan

Epic video must watch a
RT @FrustIndian: PM is so scared that he didn't give in to demand of a lowly CM to roll back #Demonetization despite qurbani warning. https
by paying through plastic money it can be monitor easily source of money   #demonetization
RT @anilkohli54: corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than person
Received my first 2000 rs note but unable to use it? No one has enough change. #demonetization
RT @kavita_krishnan: Sanghi DMs ban social media criticism of #demonetization. Only #NMApp with scripted answers is allowed I guess :) http
corrupt cowards ran away from Parliament, they will not debate #demonetization, they have nothing to say other than personal loss.
Sanghi DMs ban social media criticism of #demonetization. Only #NMApp with scripted answers is allowed I guess :) https://t.co/Xj0t9M7y9D
Digital wallet limits increased to Rs 20,000
https://t.co/LwzyJdKk4q
#Digital #Wallet #Limit #Demonetization #RBI #India #Bank #Payments
RT @HPCL: #Demonetization
HPNEs Ladies at Mmbi extend help 4 FillingForms, Water at SBI Mahul Rd. Brnch
BringingSmilles
@dpradhanbjp @Ashut
Civil cases are still pending for years &amp; years only through non corruption they can be solved  #demonetization
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
PM #NarendraModi's Speech On #Corruption &amp; #BlackMoney

#Demonetization #NoteBan

https://t.co/HjjvGzjTFS
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ruhitewari: The desperation to push this deshbhakti narrative reflects the govt is very worried about #demonetization adverse impact &amp;
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @KJshashi: Reports from last night: Naxal supporters were arrested with old Rs 1000 and Rs 500 notes worth Rs 70k. #demonetization (Hat
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
so many years people were stuck with no jobs I still dont have job but believe in MODI Not BJP  #demonetization
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
@mediacrooks Stopped watching @TimesNow as soon as Arnab Quit read why- https://t.co/y1lUMCG9SC
#boycott timesnow #Bollywood #Demonetization
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
Modi Ji is the only politician who think about common mans life and work hard to change in his standard  of living  #demonetization
#Govt announces slew of measures 2 ease #demonetization pain;no service charges fr #online #transactions till Dec 3 https://t.co/cUf8hYRnrC
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
@travisk Hi Travis, plz look into increased GPS issues on driver's side aftr #demonetization  in India. customer experience deteriorated.
All political parties played the game of cast    #demonetization have they done any thing about corruption
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
What could go wrong for #Fintech post #demonetization windfall? https://t.co/cy4aJIX0cS  @sanvai @BlackstoneVG https://t.co/SZp6BqxEH6
@narendramodi  sir i cant download the app to put my view that t i support u on #demonetization  .....any other way?
#Demonetization decision by PM without consultation with Financial Advisor, Why GOI paying him Salary if advice is not required ?@Swamy39
DEA Secy DasShaktikanta : all govt organisations advised to make payments only on digital mode, using online transactions
#Demonetization
How cashless are you? Could you convince your parents to be? #GoCashless #Demonetization  @DineshAgarwal https://t.co/1dvAq5o1WD
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
#Demonetization: Unable to withdraw money for exam fees, UP teen hangs self https://t.co/tqRFheXhqY
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @awesomeindia83: A Brilliant #OpenLetter by a #KashmiriMuslim Showing Support to #PMModi on #demonetization .. https://t.co/AuIqbo2ctJ @
we have no faith in any other political parties  as for so many years non of them has taken any action against corruption #demonetization
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
DEA Secy @DasShaktikanta : all govt organisations advised to make payments only on digital mode, using online transactions
#Demonetization
RT @ashu3page: A man shaved his head at Jantar-Mantar in protest against #Demonetization  on 13th day of the move. https://t.co/IeXuia3J0X
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @DikshitSmita: #SC despite ruling out staying proceedings in all PILs (15 so far) on #demonetization has however asked the AG to file a
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
LS Adjourns Till Noon Amid Oppn Protests ... - https://t.co/086F5Vo1ce - #DemonetisationIssue #Demonetization #LokSabhaAdjourned
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
New vehicles to have ETC-compliant RFID facility for digital deduction of charges at toll plazas: DEA Secy https://t.co/yMNkKR1kAO
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
@BigBazaar makes clears #Demonetization hurdle: enables withdrawal from stores #Guwahati
https://t.co/Mj1TPv4mEy https://t.co/3u3Wm15zwj
RT @rishibagree: A Housewife's view on #demonetization https://t.co/nFwuiZUJOD
@HRajvansh while I understand ur dislike for kejriwal, but what is ur logic behind supporting #Demonetization. I seriously want to know.
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ModiBharosa: #RatanTata supports PM Narendra Modi for #Demonetization https://t.co/fRTHY2Ltth
RT @TheChaoticNinja: When you're running away with your black money but Bae is more important. #demonetization https://t.co/9tosYC9M6h
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @FrustIndian: PM is so scared that he didn't give in to demand of a lowly CM to roll back #Demonetization despite qurbani warning. https
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
Only those are against #demonetization  who keep #BlackMoney  and they couldn't explain themselves@aajtak
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @DharmicFundoo: @narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be of n
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @renu_18: Bad thing is
The position of Worthless Unpaid Hubbies surviving on wife's money remains same aftr #demonetization &amp; r free to
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ShashiTharoor: . @anandkamal Frankly i don't understand why @narendramodi doesn't address Parlmnt on #Demonetization. It's his duty&amp;wil
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @AmanatUllah23: Addressed the #YouthCongressProtest over #Demonetization issue in Delhi. @OfficeOfRG https://t.co/MDxu4YtbPW
RT @AmanatUllah23: #YouthCongressProtest over #Demonetization issue in Delhi. (1/2) @OfficeOfRG https://t.co/6AhloTCt0s
RT @AmanatUllah23: #YouthCongressProtest over #Demonetization issue in Delhi. (2/2) @OfficeOfRG https://t.co/CVvyz430bg
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
@narendramodi ji, please place extraordinarily high security around banks in J&amp;K otherwise #DeMonetization would be https://t.co/CxQGyMHX9Y
RT @ModiBharosa: #RatanTata supports PM Narendra Modi for #Demonetization https://t.co/fRTHY2Ltth
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @sumitkashyapjha: Economic impact of #demonetization : Smaller Showrooms, shops have started firing their sales executives quietly as sa
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @ChockBlain: Indias #Demonetization: Cash is Not Holy Cow, in #Bitcoin #Blockchain We Trust https://t.co/qLwyhR2vYk #technology #Fintec
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have
RT @ModiBharosa: Putting Nation over Party Politics #nitishkumar supports PM @narendramodi on #Demonetization https://t.co/UodwXdPMmG
RT @jairajp: 2 Weeks into Tragic #DeMonetization, just 8% of Withdrawn currency has been replaced. So much for Planning &amp; Execution by #Fai
Is it fear of losing or the fear of getting exposed?? #demonetization

Did u guys realised that dhoni haters &amp; abusive star fans r not there on TL
@dna sir why u n all #aaptards are hell-bent these days 2 demonize the governments move on #demonetization.plz emphasize on #delhi problems
#Demonetization
Time will tell whether it's a big though not flawless kick to push the country out of its comfort zone
@SrBachchan
RT @SinhaPune: Praises over #demonetization from international fraternity tells one thing. <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> #oppositionxposed

@iSirArnab @hindustanse @T
RT @abhic_1983: @SitaramYechury Continue with your rants against #demonetization
People of Bengal has answered you. LOL Salaam. https://t.
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @myvotetoday: If @AnjuNagarajan DP says she supports #demonetization why is she not following us <ed><U+00A0><U+00BE><ed><U+00B4><U+0094> https://t.co/cZZvv6VUas
There goes the claim that #demonetization will stop fake notes and/or cripple terrorist funding. https://t.co/Q6E3cVZlux
RT @RealHistoryPic: Can't say anything about Productivity but Creativity has increased after #Demonetization.(2016) https://t.co/0fMh3UMbVq
Does @ArvindKejriwal spend more time on finding and retweeting tweets against #demonetization than on his duties as a chief minister?
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
Advocate J. Aslam Basha Press Meet On #Demonetization https://t.co/wmLtKNR0ES via @jab9777 @YouTube
RT @ianuragthakur: Long winding lines will continue to decrease,GOI hs taken numerous steps to ease #demonetization issues: https://t.co/sb
RT @_MiteshPatel: Do we have any reports on how much #BlackMoney is recovered by this #demonetization?

Or is it just PR drama? https://t.c
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @CMOMaharashtra: One of the greatest computer scientists Dr. Vijay Bhatkar's views on #demonetization decision by Hon PM @narendramodi h
Now terrorists are making fake 100, 500 &amp; 2000 notes. So was #demonetization a good decision? My knees are tired of queueing up again <ed><U+00A0><U+00BD><ed><U+00B8><U+00A0>
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
Even the noblest intentions get flipped in #India #RBI acknowledges fraud by bank officials in #demonetization drive
https://t.co/OCNMhR2K3n
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @RanaAyyub: In which @ravishndtv rips through the #demonetization conundrum in a way only he is capable of. Must read

https://t.co/LNpG
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
#Demonetization #cashchaos news outlets and journalists are supposed to give both sides of the story not sensationalize one side.
RT @bhaiyyajispeaks: Here @sardesairajdeep struggling for one answer against #Demonetization, He should have taken some Congress leader lik
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
#demonetization No matter what is the situation; think what good YOU can do!
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @godavar: So, a story that tells you the flipside of the digital revolution @Paytm and #Demonetization are busy celebrating. My phone go
RT @yamini_jyoti: Yes, my blood boils at @ArvindKejriwal 's maniacal statements on #demonetization .
But I ignore the fool. @RitaG74  https
RT @RealHistoryPic: Can't say anything about Productivity but Creativity has increased after #Demonetization.(2016) https://t.co/0fMh3UMbVq
RT @coolfunnytshirt: Delhiites least affected by #demonetization &amp; long queues at ATMs. They are doing online transactions with free wi-fi
@RNTata2000 #demonetization had honest objective with terrible terrible planning and execution.
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @AmarKrishnaJha: Modi's #DeMonetization was actually a strategy to bring whole of India on-line (ATM/Banks) #DigitalIndia
RT @CMOMaharashtra: One of the greatest computer scientists Dr. Vijay Bhatkar's views on #demonetization decision by Hon PM @narendramodi h
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
If they dont have cash, let them use credit cards @Sharmistha_GK quotes Antoinette on #demonetization. Brilliant! https://t.co/4Gxs7n8pbm
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
I hope few who is too much in inconvenience with Govt's move on #demonetization,  can rewind their memory... https://t.co/mcT6uLDhrC
RT @krist0ph3r: already feeling benefits of #demonetization:
1. money lasts longer
2. rickshaws don't say no any more
3. i'm walking more a
RT @abhic_1983: @SitaramYechury Continue with your rants against #demonetization
People of Bengal has answered you. LOL Salaam. https://t.
RT @ShirishKunder: "Minor inconvenience" for "major convenience" of Vijay Mallya and friends. #demonetization https://t.co/4RMD7Fpfaw
#Demonetization
Time will tell whether it's a big though not flawless kick to push the country out of its comfort zone
@Ram_Guha
RT @MinhazMerchant: Difficult to verify but if true points to orchestrated campaign to discredit #demonetization with paid fear-mongers htt
#Demonetization
Time will tell whether it's a big though not flawless kick to push the country out of its comfort zone
@shekharkapur
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
#Demonetization is only thing which taught me a lesson of minimalism
Needful stuffs But More Happiness ! Thank you PM Modi @PMOIndia
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ANI_news: The queues are not getting longer but are getting shorter day by day: Chanda Kochar,ICIC MD and CEO #demonetization https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
Finally gathered courage to stand in queue....line lambi hai...countdown starts......20........<ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082> #demonetization #noteban
RT @bainjal: Unclear why @PMOIndia can address election rallies on #demonetization but not face Parliament? Why? https://t.co/0PWe3eXzWF
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
Suspension of parking charges at airports extended till Nov 28 https://t.co/Z1EawxqjM9 #CurrencyBan #PMModi, #Demonetization #airports
RT @CMOMaharashtra: @mandybedi on Hon PM @narendramodi 's #demonetization decision ... https://t.co/j74RkdZRTO
RT @AdityaNair20: First time in 29years, our Milkman asked for a check!
#demonetization <ed><U+00A0><U+00BD><ed><U+00B2><U+009C>

@narendramodi @TarekFatah @PrasadAol @rashminp @
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization https://t.co/UTShDBMlll
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @_MiteshPatel: #Demonetization is NOT blunder.

It's deliberate drama being done for PR propaganda.
Don't down play this. https://t.co/g
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
@rssurjewala @geetv79 Isn't it true that paytm is going to be acquired by Reliance Jio?  #Demonetization
Am getting signals that RSS not happy with #Demonetization .Any info in this regard ?
#Demonetization will not be able to end corruption @ black money because the corrupt people are still running the show.
This is a terrible implementation. Every ATM runs out of cash pretty early and is only able to serve 40-50 people. #Horrific #Demonetization
The greatest shock is gullible masses electing @narendramodi as the @PMOIndia . Everything else is just consequenti https://t.co/RfkjswgMKM
RT @OnestlyBrutal: If this doesn't invite the criticism for the governmen't step, then what will? #Demonetization was a risky Idea, very po
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
already feeling benefits of #demonetization:
1. money lasts longer
2. rickshaws don't say no any more
3. i'm walking more and snacking less
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @_MiteshPatel: Do we have any reports on how much #BlackMoney is recovered by this #demonetization?

Or is it just PR drama? https://t.c
RT @_MiteshPatel: You're forgetting the Motive.

#Demonetization Drama is just a PR exercise.
Just a means through which Pro-Feku Media can
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @RealHistoryPic: Can't say anything about Productivity but Creativity has increased after #Demonetization.(2016) https://t.co/0fMh3UMbVq
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
Even the BJP leaders say #demonetization is just one step to curb black money. More loyal than the king? https://t.co/e4ZLnSoNFs
RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @spati2012: <ed><U+00A0><U+00BD><ed><U+00B1><U+0087>Steps taken by Modi government to improve public convenience on #Demonetization https://t.co/CbrxWlcDKJ
You either die a hungry man or stand in line long enough to see the cash run out. #demonetization
RT @kanimozhi: Everyone seems to hate the rich, even the rich hates richer and the richer hates the richest. #Demonetization.
How #Modiji be responsible for deaths of people standing in line for #Demonetization as these Banks &amp; ATMs were setup during #Congress rule?
RT @_MiteshPatel: Do we have any reports on how much #BlackMoney is recovered by this #demonetization?

Or is it just PR drama? https://t.c
RT @tjain2016: @narendramodi <ed><U+00A0><U+00BD><ed><U+00B9><U+008F> I'm with you,
#Demonetization was a good decision against Corruption, but why it was not planned and execut
RT @bhaiyyajispeaks: Here @sardesairajdeep struggling for one answer against #Demonetization, He should have taken some Congress leader lik
RT @ShirishKunder: "Minor inconvenience" for "major convenience" of Vijay Mallya and friends. #demonetization https://t.co/4RMD7Fpfaw
RT @mrtkachokra: Lol. When the banks themselves are involved in #blackmoney racketeering Modi says #demonetization will root out  corruptio
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @patelriship: #RemoveFixPay
Fixed pay emplys support #DEMONETIZATION #POLICY ,But When #BJP  will #Remove #FIXED #PAY REMOVAL #DECISION
RT @patelriship: #RemoveFixPay
Fixed pay emplys support #DEMONETIZATION #POLICY ,But When #BJP  will #Remove #FIXED #PAY REMOVAL #DECISION
RT @abhic_1983: @SitaramYechury Continue with your rants against #demonetization
People of Bengal has answered you. LOL Salaam. https://t.
RT @_MiteshPatel: Do we have any reports on how much #BlackMoney is recovered by this #demonetization?

Or is it just PR drama? https://t.c
RT @_MiteshPatel: #Demonetization is NOT blunder.

It's deliberate drama being done for PR propaganda.
Don't down play this. https://t.co/g
RT @RealHistoryPic: Can't say anything about Productivity but Creativity has increased after #Demonetization.(2016) https://t.co/0fMh3UMbVq
RT @kanimozhi: Everyone seems to hate the rich, even the rich hates richer and the richer hates the richest. #Demonetization.
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @ashu3page: Man ends life over fund shortage ahead of daughters wedding in Gujarat. #Demonetization
https://t.co/DGAI5cf05y
https://t
Lol. When the banks themselves are involved in #blackmoney racketeering Modi says #demonetization will root out  co https://t.co/9lhLfExMV6
RT @bhaiyyajispeaks: Here @sardesairajdeep struggling for one answer against #Demonetization, He should have taken some Congress leader lik
RT @BspUp2017: #Demonetization succinctly explained by Rebel Politik.
 #NoteNahiPMBadlo #<U+0938><U+0902><U+0938><U+0926>_<U+092A><U+0941><U+0915><U+093E><U+0930><U+0947>_PM_<U+092A><U+094D><U+092F><U+093E><U+0930><U+0947> #MayawatiNextUPCM #BSP @invi
RT @_MiteshPatel: You're forgetting the Motive.

#Demonetization Drama is just a PR exercise.
Just a means through which Pro-Feku Media can
RT @patelriship: #RemoveFixPay
Fixed pay emplys support #DEMONETIZATION #POLICY ,But When #BJP  will #Remove #FIXED #PAY REMOVAL #DECISION
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
RT @_MiteshPatel: Do we have any reports on how much #BlackMoney is recovered by this #demonetization?

Or is it just PR drama? https://t.c
RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
#demonetization in best period for two company. all our only  #patym and #patanjali
RT @amitgupta0310: 1/n One can have a cynical view on #demonetization but one should not loose the faith in the adaptability of fellow Indi
RT @kanimozhi: Everyone seems to hate the rich, even the rich hates richer and the richer hates the richest. #Demonetization.
#byelection was on 15 seats..#BJP won only 5 seats and 9 by opposition ...
#demonetization effects as Modiji  explained ?
RT @RealHistoryPic: Can't say anything about Productivity but Creativity has increased after #Demonetization.(2016) https://t.co/0fMh3UMbVq
RT @rajeev_mp: Today again #demonetization debate in Parlmnt stalled due to disruption ! <ed><U+00A0><U+00BD><ed><U+00B9><U+0084> i dont undrstnd why oppstn wants to stall its ow
RT @coolfunnytshirt: Delhiites least affected by #demonetization &amp; long queues at ATMs. They are doing online transactions with free wi-fi
I just can't figure out "What does he actually want????" #Kejriwal #Demonetization #aaptards Kaala Pani was meant f https://t.co/qo1eXNOc3v
RT @abhic_1983: @SitaramYechury Continue with your rants against #demonetization
People of Bengal has answered you. LOL Salaam. https://t.
RT @_MiteshPatel: You're forgetting the Motive.

#Demonetization Drama is just a PR exercise.
Just a means through which Pro-Feku Media can
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;

RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @UnSubtleDesi: Kejriwal posts pic of dead robber and claims it's #demonetization related death? How shameless has this man become? https
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @ruhitewari: The desperation to push this deshbhakti narrative reflects the govt is very worried about #demonetization adverse impact &amp;
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @Vidyut: Modi is India's (possibly the world') first Prime Minister to single handedly bring about a recession. #demonetization https://
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
.@WorldBank @UN Now #NarendraModi Hoodwinks You with #Demonetization Survey https://t.co/iOsmmmgmhc
RT @meet_murtaza: Given the current wave of #demonetization in the country, the quickest way to double your money is to fold it &amp; keep it b
a good lawyer taking care of the Finance Ministry... #demonetization Queue Kyu Queue Kyu https://t.co/xx990iUGw7 #blogging #blog #writing
RT @yamini_jyoti: Yes, my blood boils at @ArvindKejriwal 's maniacal statements on #demonetization .
But I ignore the fool. @RitaG74  https
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @DrGPradhan: .@ravishndtv of @ndtv spreading rumours to provoke people against #demonetization &amp; PM @narendramodi

He need mob treatmen
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
Nageswaran+Natarajan write provocatively on #demonetization https://t.co/5YbOcHeOlw

Based on @CarnegieIndia report https://t.co/esMx0MG3EW
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @IamRitzV: LOL!!
Real reason is #Demonetization
They have no money to celebrate his birthday!!
<ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082> https://t.co/sIVo5YMhJp
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @JammuKashmir5: #Demonetization move has dealt a body blow to the nefarious designs of #Pakistan-#Separatist nexus.

#KashmirUnrest #Gui
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
Congratulations India has gone back to barter system civilisation  #Demonetization #notenahiPMbadlo https://t.co/v7xPTiRnoV
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
A very positive development! Better than #demonetization https://t.co/bKEKe2djCV
RT @yamini_jyoti: Yes, my blood boils at @ArvindKejriwal 's maniacal statements on #demonetization .
But I ignore the fool. @RitaG74  https
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
RT @RuchiKom: Every honest citizen of India ready to bare small inconvenience due to #demonetization &amp;are with PM @narendramodi in fight ag
I fear SBI ATMs-slowest machines ever. &amp; fear has doubled post #demonetization times, what if machine simpl conks off? #toomuchworkload u c
RT @AnupKaphle: A service in India lets you hire a person to stand in an ATM line for 90 rupees. https://t.co/s7FHe35JqC #demonetization
@narendramodi we are @jankibaat1. Where awe will give largest citizen videos on #demonetization https://t.co/P8U2xvBHWA
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/RzJsVGxUSc
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @GauravGogoiAsm: #DeMonetization aimed to stop terrorists with cash but media reports show terrorists in J&amp;K with new Rs 2000 notes. Fla
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @ShashiTharoor: Joined Kerala MPs protesting the exclusion of co-operative banks from #demonetization arrangements. 90% of rural savers
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @_SwarajIndia: Government's seriousness about black money: Reality or a Sham?
@AnupamConnects speaks on #demonetization https://t.co/ZGq
RT @MinIT_Telangana: Telangana govt's innovative solution to help farmers affected due to #Demonetization: https://t.co/NVv7slCcpr
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @aartic02: But Modi &amp; Chamchas told Terrorism wiped off after #Demonetization https://t.co/X2ME55oPks
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
#RBI Sets Firm Guidelines For Withdrawal Of Cash For #Weddings #demonetization https://t.co/xM6AQVX1h4 https://t.co/jvCft1Qv8I
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @BSLMF: Our #Equity Chief Mahesh Patil spoke to @_prashantnair on #Demonetization on @CNBCTV18Live today https://t.co/Q48pBepg1p  #Marke
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
I took part in the survey on @narendramodi App &amp; shared my opinion on the #Demonetization .u can also do it now! https://t.co/mk5vNxpk0x
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @PankajPachauri: Very careful rollback on #demonetization by @BillGates
Day1- "Bold Step."
Day2- "No Opinion." https://t.co/Azai2rBZV1
#Demonetization Money blocked,.Govt no match for the huge public support.It is because the act is real good. - https://t.co/AZVNG5lOWD
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
#Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/hI3d2yTuic @ArvindKejriwal @PreetiSMenon @aartic02
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
RT @TimesNow: #NetasCASHIn Govt wants debate over #DeMonetization but Oppn running away https://t.co/uCS21Uv5G8
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @jan14anurag: Terrorists raided a bank to get new  <U+20B9>2000 notes =&gt; their old finances are indeed squeezed tight #Demonetization
https://t
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
RT @TimesNow: #NetasCASHIn Govt wants debate over #DeMonetization but Oppn running away https://t.co/uCS21Uv5G8
I am planning 7-8 weddings ..hunting guys ha ha
acchhe din  for Matrimonial &amp; wedding planners #demonetization https://t.co/FF3ygA4xpW
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DaaruBaazMehta: Cash crunch hits Asia's biggest wholesale market

Azadpur Mandi comes to a standstill after #demonetization

cc @Arvin
RT @SatyendarJain: People who are supporting #demonetization  will definitely wake up, when lay off will start because  of economic slowdow
RT @TimesNow: #NetasCASHIn Govt wants debate over #DeMonetization but Oppn running away https://t.co/uCS21Uv5G8
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @IYC: Is Indian Railways still unaware about #demonetization ???

Will @sureshpprabhu @manojsinhabjp take note of it

CC @narendramodi @
Beautiful! Guess only women from god's own country can protest like this. #demonetization https://t.co/XqMcSYhOKA
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
It's always good to be light.
Try our #Liposuction service.
Visit https://t.co/4KoUIuoJcf
Call now at +91 11 406663 https://t.co/VSJaA6gV2V
RT @MoviezAdda: @BeingSalmanKhan The SAVIOUR - Gives #money To #Farmhouse #Poor Peoples In #Demonetization
Check Out <ed><U+00A0><U+00BD><ed><U+00B1><U+0089>https://t.co/c7lyi9CQ
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @kavita_krishnan: Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @DaaruBaazMehta: Dy CM @msisodia  detaiend at Parliament Street Police station as they march to Parliament against #Demonetization

#not
RT @kavita_krishnan: Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
RT @kavita_krishnan: Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
RT @kavita_krishnan: Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
*Random Thoughts*

Enough jokes on #Demonetization, also no more posts on politics or social affairs...
Probably... https://t.co/auuxRNYi5Q
RT @VandanaSsingh: People at airport too facing problem. No cash available for exchange money. They are also out of cash. #Demonetization h
RT @Ra_THORe: #Demonetization #IndiaFightsCorruption Immense courage needed to take such a momentous decision @arunjaitley @narendramodi @P
But THE FUCK we should PAY for corrupt people crimes, like what's the fucking point!? #Demonetization ! Punish them, not us for God's sake
RT @dna: #Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @Ra_THORe: #IndiaFightsCorruption The honest feel vindicated by the historic move on #Demonetization : @arunjaitley ji @ BJP Parliamenta
RT @RJSudeshBhat: #demonetization Did this using a @KicchaSudeep and @TheParulYadav song :) Take a look :) https://t.co/UROvCy21T4
RT @BSLMF: Our #Equity Chief Mahesh Patil spoke to @_prashantnair on #Demonetization on @CNBCTV18Live today https://t.co/Q48pBepg1p  #Marke
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @kavita_krishnan: Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
Non corrupt and common innocent people are suffering, but black money holders are suffering more. Okay! i understand! #Demonetization!
Modi #demonetization explained - Mr Bean style https://t.co/nfQISyHdC4
RT @ItsBollyLive: #SalmanKhan Comes In RESCUE Of Poor Peoples Near His Farmhouse | Gives MONEY During #Demonetization https://t.co/7HPb8bFG
#Demonetization: Paan shop owner gets 'fake' Rs 2,000 note in Ahmedabad https://t.co/ePVcU2T38F
RT @PankajPachauri: Very careful rollback on #demonetization by @BillGates
Day1- "Bold Step."
Day2- "No Opinion." https://t.co/Azai2rBZV1
RT @DipendraDipzo: #Demonetization effect
Here comes another batch of Maoists..
Keep on watching - More to come
#NoMoneyYaar https://t.co/
RT @ippatel: Retaining all seats of LS and state in Byelection by BJP has proved the people's support on #DeMonetization. It should be abov
Effect on Consumer Goods and Real Estate by #Demonetization of 500 and 1000 rupees notes in India. Official Blog: https://t.co/8ThYV501pS

RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
RT @IamRitzV: LOL!!
Real reason is #Demonetization
They have no money to celebrate his birthday!!
<ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082> https://t.co/sIVo5YMhJp
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @askdheeraj: #Hilarious video. #hitlerfindsout  #demonetization @inquestioner https://t.co/NSiccFStBf
RT @sistlamurali: Congress MLC C.Ramachandraiah Slams #3Dbabu On #Demonetization

 https://t.co/o019swkhUO via @YouTube
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @Modern_Gypsy: #demonetization will help combat terror because Pak won't be able to print new notes! And now, this. *slow claps* https:/
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
#Demonetization Is not end but beginning of struggle against Black Money #modi

For More Details Visit@====<U+25BA> https://t.co/NXcvGaKkS8
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
#Delhi Deputy CM #ManishSisodia leads #aamaadmiparty march to parliament against #demonetization https://t.co/EPs3i4tEtB
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
@ANI_news If they claim all credit to PM &amp; after all PM &amp; FM r d only ones 2 know d #demonetization, why shouldn't he turn up to parliament?
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @UrjitPatelRBI: What do think of the #demonetisation of notes? #demonetization poll #RBI #Modi
RT @jairajp: Proving again that #DeMonetization has no adverse impact on Terrorism or Terror Funding as claimed by modi ji &amp; his Propaganda
OK  now dont complain that modi ji promised 2 Crore jobs a year but did only 1.35 Lakh. He is making up for thru https://t.co/RiON3cqAlH
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
#Amul milk producers to get payment directly from the #banks | https://t.co/XSjbTUzqsC @Amul_Coop #Demonetization... https://t.co/ZscvPUst86
#Amul milk producers to get payment directly from the #banks | https://t.co/TVGb4puFSh @Amul_Coop #Demonetization https://t.co/cAUNPzayNI
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
#Amul milk producers to get payment directly from the #banks | https://t.co/6F1bpn3lDZ @Amul_Coop #Demonetization https://t.co/MIzTjrf5AL
#Amul milk producers to get payment directly from the #banks | https://t.co/BWAxqZqCZU @Amul_Coop #Demonetization https://t.co/RTEw1nCuL2
#Amul milk producers to get payment directly from the #banks | https://t.co/T7tPQ0MVjS @Amul_Coop #Demonetization https://t.co/1PANHyTggY
#Amul milk producers to get payment directly from the #banks | https://t.co/XSjbTUzqsC @Amul_Coop #Demonetization https://t.co/XnuoYxGjKj
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @jitenderkhalsa: Dy CM @msisodia  detaiend at Parliament Street Police station as they march to Parliament against #Demonetization . htt
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @kanimozhi: India will get windfall profit of whooping 4 Lakh crores in 30 days due to #demonetization Why people like AK Pappu &amp; Mamata
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
RT @jackerhack: Indore's collector would like you to shut up about #demonetization. At @internetfreedom we think that is a problem. https:/
RT @RealZaidHamid_: #DemonetizationMythsBusted
Anyone dying within 20 km radius of bank is coz of #Demonetization and Modi is directly resp
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;
All weddings now need to be approved by RBI... Amazing times #demonetization isn't that what we are understanding
RT @DrKumarVishwas: And the Oscar goes to "Mr.<U+092D><U+093E><U+0935><U+0941><U+0915>" <ed><U+00A0><U+00BD><ed><U+00B8><U+00A9><ed><U+00A0><U+00BD><ed><U+00B8><U+00A5><ed><U+00A0><U+00BD><ed><U+00B8><U+00A2><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>#demonetization https://t.co/ObQrhlNSL6
RT @jan14anurag: Terrorists raided a bank to get new  <U+20B9>2000 notes =&gt; their old finances are indeed squeezed tight #Demonetization
https://t
RT @jackerhack: Indore's collector would like you to shut up about #demonetization. At @internetfreedom we think that is a problem. https:/
@quizderek Post #Dmonetization the result will be totally different.The win is not because of #demonetization an all knows about it
@baliramsingh2 So many restrictions. Not easy to avail the facility by anyone. Multiple U-turns by GOI on the issue. #DeMonetization #RBI
FYI, I must tell and clear your doubts to enhance your GENERAL KNOWLEDGE that this wholesome experiment of #DEMONETIZATION is only
RT @sukanyaiyer2: #DeMonetization AAP protests by marching Against Govts move over DeMonetization &amp; he is also detained as he Tried 2 March
#demonetization will help combat terror because Pak won't be able to print new notes! And now, this. *slow claps* https://t.co/p0p93sXiMn
#Demonetization Positive Effect: Cigarette Sales Slashed To Almost Half After Demonetization:Report @deepparihar @Tabassumzia @AshSharma1102
RT @UnSubtleDesi: Kejriwal posts pic of dead robber and claims it's #demonetization related death? How shameless has this man become? https
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
A few 'Experts' derided demonetization, claiming black money isn't stored as cash!
@myogiadityanath govt means busi https://t.co/8aA3LVsy1m
One idea for going cashless: Incentivize digital payment methods, a la India https://t.co/rRtQ3k9gFZ
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl
RT @jamewils: @Memeghnad After all the euphoria and fad about black money, FICN, etc during demonetization, IT Dept able to serve notice on
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
@surya_vanshi_ @cpmgup This much inconvenience I didn't even faced at the time of getting jio sim or cash withdrawa https://t.co/1qW9aTzQMW
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
@jamewils @CNNnews18
No media coverage so far on how much tax payers money wasted in govt. foolish decision of demonetization.
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
RT @jamewils: @Memeghnad After all the euphoria and fad about black money, FICN, etc during demonetization, IT Dept able to serve notice on
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl
@narendramodi whole india is with you. We voted for you. We need to see some thing like demonetization for kashmir too. @majorgauravarya
@Priyavarshini10 @ndtv Demonetization was brought again black money....So I hope there's no black money left in cou https://t.co/j2LX1LZkTO
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
@ETMarkets had not listen to @Raamdeo @porinju @VijayKedia1 I was always skeptic n terified never made money wic I made after demonetization
@HPCL @dpradhanbjp @PetroleumMin @aloktripathi74 @AshutoshJindalS @khabarindia1 @PIB_India @pcraindia @swachhbharat https://t.co/WZBqr1486v
#Demonetization Conference at #JindalGlobalBusinessSchool #JGBS discusses societal and economic impact https://t.co/HWk4QIVB2k
RT @DeFotis: #EmergingMarkets' Stellar 1Q: #India &amp; Mexico Are Comeback Kids https://t.co/lc0Dp9Q7V8 #ETFs #demonetization #Asia $EEM @barr
#Demonetization Conference at #JindalGlobalBusinessSchool #JGBS discusses societal and economic impact
https://t.co/EaAX6fJLvh
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @jamewils: So they pick pocketing us in the guise of demonetization and service charges <ed><U+00A0><U+00BD><ed><U+00B8><U+009C> https://t.co/EqbMve2T2F
RT @rahulroushan: Demonetization problems are officially over, else Rahul ji would have stayed back in solidarity of people. https://t.co/E
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
Demonetization didn't stop corruption, didn't stop stone pelting. What did it stop? #BJPFails
Didn't BJP claim demonetization had stopped stone pelting in Kashmir? Was that a lie? #BJPFails
@azad_mayank I do it only when I m v much confident..Mana i avgd downwards during demonetization..Avgd maithan upwards this tym
RT @jamewils: @Memeghnad After all the euphoria and fad about black money, FICN, etc during demonetization, IT Dept able to serve notice on
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
Demonetization Conference at Jindal Global Business School (JGBS) discusses societal and economic i... | @scoopit https://t.co/4bgSenDapZ
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @ysingh7680: I will not support "Bharat Band".  That day I will work extra for two hours. Because, I know very well about benefits of de
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @Gopalee67: @VenkatN_Tss @CNNnews18 Failure of demonetization?
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @nixxin: But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
RT @5Forty3: From Jan Dhan to Ujjwala to Neem coated Urea to e-Mandis to Demonetization, Modi's impact on India is historically unprecedent
RT @ShootinThoughts: Sonu should be accused of attempt to murder, just like Demonetization was held responsible for deaths
https://t.co/ggj
But wasn't demonetization supposed to fix exactly this? https://t.co/ejlAIQOs2M
@VenkatN_Tss @CNNnews18 Failure of demonetization?
Indian #Silver Imports Fail To Improve Post Demonetization https://t.co/Q9ZPJwGFkK #podcasts
@narendramodi After almost 6 months can this govt explains the benefits of demonetization........
We all are waiting Mr. PM
RT @5Forty3: From Jan Dhan to Ujjwala to Neem coated Urea to e-Mandis to Demonetization, Modi's impact on India is historically unprecedent
RT @5Forty3: We suspect that the positive economic impact of demonetization is going to be far more overwhelming than the political or elec
@_microcosm__ According to him, Usa is behind aadhar. Demonetization. Modi's win. He gives facts and hypotheses that makes sense.
@DrKumarVishwas After almost 6 months can this govt explains the benefits of demonetization........
We all are waiting Mr. PM
@ArvindKejriwal After almost 6 months can this govt explains the benefits of demonetization........
We all are waiting Mr. PM
@ndtv After almost 6 months can this govt explains the benefits of demonetization........
We all are waiting Mr. PM
RT @Stupidosaur: @rkam105 @nixxin @ALPHA_Ronin Also it is beyond doubt that demonetization happened by USA orders, part of its cashless pus
@rkam105 @nixxin @ALPHA_Ronin Also it is beyond doubt that demonetization happened by USA orders, part of its cashl https://t.co/5C6aHXveq3
After almost 6 months can this govt explains the benefits of demonetization........
We all are waiting Mr. PM
All d builders who bought land in Panvel will start selling &amp; make up for their loss of sales in Mum aftr demonetiz https://t.co/MpGCVma5D0
RT @jamewils: So they pick pocketing us in the guise of demonetization and service charges <ed><U+00A0><U+00BD><ed><U+00B8><U+009C> https://t.co/EqbMve2T2F
RT @aadityagautom: Assam Govt initiatives 4 Tea tribe workers after Demonetization at National Geographic's program 'INDIA REMONETIZED'. Cr
@ashoswai That's what 11383583 people of India said in 2017 abt demonetization when they voted for the person who y https://t.co/bMGdVYG04K
Question for progressive YouTubers currently being targeted by demonetization: Have you thought about moving to Dailymotion or Vimeo?
@tylrfishr FB's algo-, Twitter's moderating- and YT's demonetization-policy paradigm shift resemble the closing-dow https://t.co/EF0AibFpK0
RT @Memeghnad: 11) And then, rest is history unfolding before our eyes. Everyone is happy now people. Let us all rejoice!
https://t.co/Zbfo
Former RBI governor YV Reddy says note ban had almost no impact on black money, graft https://t.co/hHKqm35A7K #Demonetization #SayNotoModi
@AmmU_MaanU <U+0BA8><U+0BC7><U+0BB1><U+0BCD><U+0BB1><U+0BC1> NGC documentary abt demonetization <U+0BAA><U+0BBE><U+0BB0><U+0BCD><U+0B95><U+0BCD><U+0B95><U+0BB2><U+0BC8><U+0BAF><U+0BBE>
RT @jamewils: @Memeghnad After all the euphoria and fad about black money, FICN, etc during demonetization, IT Dept able to serve notice on
@narendramodi Ppl have been appreciating ur move on demonetization and ur choice for UP. Ppl r taking about such a move 4 TN.Right time4bjp
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl
RT @Memeghnad: 11) And then, rest is history unfolding before our eyes. Everyone is happy now people. Let us all rejoice!
https://t.co/Zbfo
@KunalGhoshal2 - every possible ways starting from rising daily necessity and commodity prices to demonetization, killing 116 people and...
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl
RT @jamewils: @Memeghnad And finally.. If Government seriously believe that PAN is compromised in the manner AG is vocal, please do a demon
@priyankac19 This coming from someone who's own party leader travelled in 1.5 cr SUV to withdraw Rs 4000 during #Demonetization <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082>
Demonetization 2 Remonetization-Great transformation. Request our beloved PM @narendramodi 2 start campaign 4 Deforestation to Reforestation
The recording is up! "Demonetization, Digital Identity &amp; UBI How Big Ideas Are Changing India and what it means": https://t.co/w3tPAJR4KT
Black money:Demonetization::Pan card fraud:mandatory Aadhar
@ANI_news Demonetization? <ed><U+00A0><U+00BD><ed><U+00B8><U+0081>
@ICICIBank Demonetization helped u this much that hav started deducting fake service charges.Is this digital India. @narendramodi @rsprasad
RT @CashlessConsumr: .@nikhilkumarks: BHIM was made because of confusion among people which product to use. 22 UPI apps were launched durin
RT @jamewils: @Memeghnad PAN duplicate argument reminds me exactly like the Demonetization argument about FICN, which is buried convenientl

RT @PathaniaSagar: @sureshpprabhu sir in demonetization i canceled my tickets and they gave me TDR its almost 100 days but didn't receive m
@sonaliranade #Demonetization was Modi's one-trick pony to solve it all and, in a Trumpesque manner, he failed rema https://t.co/jIfCsmgvVU
@myogiadityanath Ecotech G Noida industrial plot completion date 31 march could not complete due 2 demonetization SME affected 4 fund extend
What are the figures for the VCES after demonetization ? @adhia03
RT @Janamejayan: 5. Demonetization drew these people's money into banks vaults as deposits with which vast bad loans were written off.
RT @inNatGeo: Observe how demonetization affected the entire country on India Remonetized  premiering on 20th April at 9 PM. https://t.co/
RT @NG_withINC: After demonetization first modi waived off Mallya's loan and now got him bailed out!
Is modi Mallya's pet dog?
#VijayMallya
@Swamy39 M.S.E.M thought  they could achieve their Purpose with  Demonetization Issue. But With People's Cooperatio https://t.co/UIUdCrUqPA
Liked on YouTube: Life After Demonetization in India | Nazar Battu | Dalveer - Satbeer https://t.co/sVqWJenq3f
RT @Lukewearechange: my news team and I lost the majority of our income through youtube demonetization recently, if you could help plz do
h
Demonetization failed in each of it's stated objectives,but achieved the unstated objective of winning UP elections. https://t.co/E3Wie3tmAS
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
@ShainaNC @narendramodi @AmitShah @AmitShahOffice  @amitabhk87 @bjpsamvad @PMOIndia we were already cruising at 7.7% before demonetization
@narendramodi sir,MSE r affected during our historic demonetization drive. Contracts could not be completed on-time.heavy penalty is imposed
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
This can be Indicator of AfterEffects of  #Demonetization  .How Employment specially Rural,unskilled sector hit... https://t.co/02rmaOkyui
This can be Indicator of AfterEffects of  #Demonetization  .How Employment specially Rural,unskilled sector hit by https://t.co/CbBsuiwtmf
RT @TCS: In the wake of #demonetization in India, here's how NBFCs are filling the void left behind by the informal #lenders. https://t.co/
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
The recent scenario with tight #liquidity and RBI cuts can have an adverse effect on #employeebenefits liabilities- https://t.co/iNdUajqK7s
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
RT @ePaisa: Why Demonetization is Good for Everyone - ePaisa | enabling commerce https://t.co/PbsZ1qzkGe
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@arvindsubraman on Demonetization, Digital Identity and Universal Basic Income https://t.co/XUwUomRyot via @YouTube
Watch Hilarious Debate on demonetization - watch Video -

https://t.co/KRYDgybLuu
Watch Hilarious Debate on demonetization - watch Video -

https://t.co/fmRDYGb09H
How Demonetization Affected Travelers From Around The World https://t.co/dbuSSTfWTo #lifehacks
No Cash in SBI shikohabad(Branch code 00716) after 162 days of #demonetization &amp; all SBI Atm are out of service https://t.co/CTv922CCNu
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
The latest The Demonetization Daily! https://t.co/tImaqQLybe Thanks to @newshqtoday #topnews
@GabbarSanghi I'll effects of demonetization <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082>
RT @amit_2912: Dear @narendramodi ji &amp; @myogiadityanath ji,I m a banker, felt much pressure in #demonetization got overtime but our guards
RT @AbuRC1981: @ravishndtv making #SchoolFeeloot a great awareness programme to all parents. Hats of. Hope @PMOIndia do something like demo
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @SecretaryMEITY: #Demonetization lead to a swift deployment of digital payments technology &amp; will have positive impact :@WorldBank
http
News, specially<U+200B> for SP, BSP  and others political parties who blame BJP to protect BJP's political s during the pe https://t.co/BgyarUwdFP
@Publicitylover @ArvindKejriwal @myogiadityanath Demonetization? - So you're a banker??
Good roads in UP after 2017 https://t.co/4CvMPqrjrH
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
Maximum Voolsy order payments are done online since #demonetization
#DigitalistIndia #Voolsy
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
I liked a @YouTube video https://t.co/gv5PdIGyH0 Podcast #107 - The Censorship/Demonetization of YouTube
RT @TCS: In the wake of #demonetization in India, here's how NBFCs are filling the void left behind by the informal #lenders. https://t.co/
@gauravvns So you mean same thuggery as demonetization scam by USA goons. #ScrewedByUnitedStates
RT @Janamejayan: 14. Menwhile the PM and his droolers claim those opposing demonetization were political worshippers of graft &amp; black money.
RT @Janamejayan: 13. Demonetization had no impact on those vast black monies turned into commodities.
RT @Janamejayan: 8. This put BJP at an advantage over competing parties where elections were being held shortly after demonetization.
RT @Janamejayan: 6. Before demonetization there had been selective leaks so friend of ruling party were able to get the new money easily.
RT @Janamejayan: 5. Demonetization drew these people's money into banks vaults as deposits with which vast bad loans were written off.
RT @Janamejayan: 1. I have tweeted commenting on demonetization as being politically motivated for following reasons:
RT @TCS: In the wake of #demonetization in India, here's how NBFCs are filling the void left behind by the informal #lenders. https://t.co/
In the wake of #demonetization in India, here's how NBFCs are filling the void left behind by the informal #lenders https://t.co/hyVgpyTuuW
Why Demonetization is Good for Everyone - ePaisa | enabling commerce https://t.co/PbsZ1qzkGe
Following through on all principles following the demonetization #cpol120 https://t.co/9NL6btNRds
RT @SecretaryMEITY: #Demonetization lead to a swift deployment of digital payments technology &amp; will have positive impact :@WorldBank
http
@ravishndtv making #SchoolFeeloot a great awareness programme to all parents. Hats of. Hope @PMOIndia do something like demonetization.
RT @616476fbde873af: My experience during this #demonetization (edit)
#WalnutApp #MobiKwikHaiNa https://t.co/v7JRsyOiAg
RT @GauravPandhi: When India queued up outside Banks during demonetization, BJP Govt waived-off Mallya's bad debts amounting <U+20B9>1200 crores.
RT @RNTata2000: The governments bold implementation of the demonetization programme needs the nations support. https://t.co/tx1ZILSor8
@IndianExpress Demonetization could've been done anytime but this guy mallya is father of leaders who is paying som https://t.co/6MKgyC0evJ
@IamlalitG @ArvindKejriwal @msisodia @SharmaWrites Thanks to demonetization.
At 44 degree Celsius -- admire the discipline and not a single complaint - Press too quite b'cause it's not demonet https://t.co/qF7mEkjFYb
RT @SecretaryMEITY: #Demonetization lead to a swift deployment of digital payments technology &amp; will have positive impact :@WorldBank
http
@madhu_gopalan @knowsnotmuch Communication breakdown during demonetization was both terrible &amp; eye opening (to see https://t.co/nRRSiuctbG
RT @ms_rana: Heart warming story from Hyderabad. When ATMs were dry (thanks to Modi's demonetization), the auto-driver helped. https://t.co
RT @sffed: #Demonetization is catalyzing digital #payments growth in #India. https://t.co/fYBDNtv8MO #SFFedAsiaProgram https://t.co/0gbkajY
RT @sffed: #Demonetization is catalyzing digital #payments growth in #India. https://t.co/fYBDNtv8MO #SFFedAsiaProgram https://t.co/0gbkajY
@dna He is too depressed due to demonetization!
RT @jokinjey: @S_Rvignesh @karupalaniappan Anna university VC post auction base price 60 Cr.. If you know anyone , tell them to bid. Thanks
RT @Phronesis_inc: As #Indias #wholesale #price #index falls steeply last month, is it the aftermath of #demonetization or merely a season
@SitaramYechury it has brought everything to a halt or Taken us back by a decade.Demonetization being the prime example.
Yesterday I was speaking to a famous Doctor and she mentioned how demonetization had impacted well deserved treatme https://t.co/AVtmtnokPg
Actual effect of demonetization will be seen now in quarterly results of banks. Yes and Indusind banks will be in focus today! #Nifty
RT @SanaSecurities: Opportunities from demonetization in the long term https://t.co/0juSLrVQl6 via @sanasecurities
RT @ms_rana: Heart warming story from Hyderabad. When ATMs were dry (thanks to Modi's demonetization), the auto-driver helped. https://t.co
Heart warming story from Hyderabad. When ATMs were dry (thanks to Modi's demonetization), the auto-driver helped. https://t.co/VH62tVRn0z
I added a video to a @YouTube playlist https://t.co/0zKwJCB9l2 <ed><U+00A0><U+00BD><ed><U+00B9><U+008A> The Truth About YouTube Demonetization, AdSense Boycott &amp;
I liked a @YouTube video https://t.co/0zKwJCB9l2 <ed><U+00A0><U+00BD><ed><U+00B9><U+008A> The Truth About YouTube Demonetization, AdSense Boycott &amp; Censorship
Reminder Re: complaints of demonetization, YouTube is a criminal racket.  Google is the biggest lobbyist in DC for a reason.
RT @NG_withINC: After demonetization first modi waived off Mallya's loan and now got him bailed out!
Is modi Mallya's pet dog?
#VijayMallya
RT @ScrewedbyState: In India the authoritarian Modi govt is severely infected with the virus of digital socialism-demonetization,cashless,
RT @NG_withINC: After demonetization first modi waived off Mallya's loan and now got him bailed out!
Is modi Mallya's pet dog?
#VijayMallya
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
A Well-Kept Open Secret: Washington Is Behind Indias Brutal Demonetization Project | Asia-Pacific Research https://t.co/mtfVB9wWGr
RT @SamKhan999: By the way where is the genius who had declared Demonetization ended stone pelting in #kashmir
RT @ScrewedbyState: In India the authoritarian Modi govt is severely infected with the virus of digital socialism-demonetization,cashless,
In India the authoritarian Modi govt is severely infected with the virus of digital socialism-demonetization,cashless, Aadhaar(biometric ID)
RT @SecretaryMEITY: #Demonetization lead to a swift deployment of digital payments technology &amp; will have positive impact :@WorldBank
http
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @NemRaps: - EXTREME demonetization
- No realtime analytics
- Now disappearing comments?

Is YouTube is slowly trying to kill my channel?
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Stealth demonetization Illustrated https://t.co/lmUZGz1Vha #BitChute
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
RT @jokinjey: @S_Rvignesh @karupalaniappan Anna university VC post auction base price 60 Cr.. If you know anyone , tell them to bid. Thanks
#Demonetization and tales of woe - stories at a bank https://t.co/JjohTqEPNw via @SiyaWoman
@S_Rvignesh @karupalaniappan Anna university VC post auction base price 60 Cr.. If you know anyone , tell them to b https://t.co/YfM0pf7U3D
RT @Memeghnad: 11) And then, rest is history unfolding before our eyes. Everyone is happy now people. Let us all rejoice!
https://t.co/Zbfo
The latest The Demonetization Daily! https://t.co/tImaqQLybe #news #topnews
RT @Satyapriyan: Demonetization is the biggest economic fraud played on the citizens of India. @IndiaToday, praising govt on this is a bigg
#Demonetization is catalyzing digital #payments growth in #India. https://t.co/fYBDNtv8MO #SFFedAsiaProgram https://t.co/0gbkajYeGG
RT @smarket: Here's SBI Chairman explaining clearly that current demonetization has nothing to do with NPA. Please listen https://t.co/AqCn
RT @bitchute: @JeffereyJaxen Thanks Jefferey, the move against Tubers started around 2014. It won't stop with demonetization. Diversify and
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
@bitchute @JeffereyJaxen No I Don't think they will and I support @bitchute too, but its a bad comparison to say 'd https://t.co/QnGN8XlQ3g
RT @OfficeOfRG: Fully prepared for demonetization!
https://t.co/YHT0sHudWL
I liked a @YouTube video https://t.co/BTciGVSIWJ Demonetization - Stand Up Comedy by Amit Tandon
@JeffereyJaxen Thanks Jefferey, the move against Tubers started around 2014. It won't stop with demonetization. Div https://t.co/pEy96JkK7j
RT @GauravPandhi: When India queued up outside Banks during demonetization, BJP Govt waived-off Mallya's bad debts amounting <U+20B9>1200 crores.
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
@rupasubramanya Did Vajpayee bring in GST ? Demonetization ? Aaadhar expansion ? ..... Also what did nation give ba https://t.co/R2BLl5j4nU
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
RT @CSISIndiaChair: March'17 PMI indicates India's manuf. sector has fully recovered from demonetization, though still 4th in Asia https://
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @Janamejayan: 1. I have tweeted commenting on demonetization as being politically motivated for following reasons:
@JackPosobiec It's going to be some poo, but there isn't much to be done.. It will run in parallel with the youtube https://t.co/ZK6ids4cVn
RT @Janamejayan: 5. Demonetization drew these people's money into banks vaults as deposits with which vast bad loans were written off.
RT @Janamejayan: 6. Before demonetization there had been selective leaks so friend of ruling party were able to get the new money easily.
RT @Janamejayan: 8. This put BJP at an advantage over competing parties where elections were being held shortly after demonetization.
RT @Janamejayan: 13. Demonetization had no impact on those vast black monies turned into commodities.
RT @Janamejayan: 14. Menwhile the PM and his droolers claim those opposing demonetization were political worshippers of graft &amp; black money.
RT @Janamejayan: 1. I have tweeted commenting on demonetization as being politically motivated for following reasons:
RT @Janamejayan: 13. Demonetization had no impact on those vast black monies turned into commodities.
14. Menwhile the PM and his droolers claim those opposing demonetization were political worshippers of graft &amp; black money.
RT @Janamejayan: 13. Demonetization had no impact on those vast black monies turned into commodities.
13. Demonetization had no impact on those vast black monies turned into commodities.
8. This put BJP at an advantage over competing parties where elections were being held shortly after demonetization.
6. Before demonetization there had been selective leaks so friend of ruling party were able to get the new money easily.
1. I have tweeted commenting on demonetization as being politically motivated for following reasons:
RT @priyaakulkarni2: Post demonetization

Economy to grow at 7.4 acc to Asian Development bank.

World Bank says note ban will have positiv
RT @Sarah__Reynolds: YOUTUBE RED ALERT: https://t.co/5bZP8StDk5 @d_seaman has an update regarding @YouTube's new demonetization/auto-unsubs
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
@mundanematt I hate how much this youtube demonetization shit is changing everything. I mean, you do what you gotta https://t.co/s35vfrbZMz
RT @MilanV: Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @
@TimesNow Some media channels was showing that the growth of GDP is too higher than before after demonetization
RT @LivingOnChi: 1/21/17 Demonetization: The Sinister Agenda Behind Washingtons War On Cash
https://t.co/AmsasJj4wt
@Cottonsean @robertoblake It's Shelly Saves the Day.
I was talking about Why Im not mad about YouTube Demonetizat https://t.co/6YrDLgILC5
@itversity Demonetization
Even Snapchat feel for our status after demonetization. Modi made everyone poor. Our beloved black money. :(
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @NG_withINC: After demonetization first modi waived off Mallya's loan and now got him bailed out!
Is modi Mallya's pet dog?
#VijayMallya
Bummed that I missed @arvindsubraman's conversation w/ @AnnieLowrey @CGDev, but the video is here https://t.co/aCQ2FRRVmO via @khoslasaksham
RT @NG_withINC: After demonetization first modi waived off Mallya's loan and now got him bailed out!
Is modi Mallya's pet dog?
#VijayMallya
I'm upset about the whole demonetization thing that has been happening on youtube for the past few months, so I will be making videos(1/2)
RT @JediLucario1138: End YouTube's Demonetization of Channels https://t.co/TZ4AKxOMeg
Indian #Silver Imports Fail To Improve Post Demonetization https://t.co/gHpBPDNrDy #podcasts
RT @StateBank_Pak: Public Awareness regarding Demonetization of Old Design and Bigger Size Banknotes (Rs 10, 50, 100 &amp; 1000)
Details:
https
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @SecretaryMEITY: #Demonetization lead to a swift deployment of digital payments technology &amp; will have positive impact :@WorldBank
http
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually

I liked a @YouTube video https://t.co/StKhGfQ3wr Future of YouTube: Demonetization, Advertiser Boycott &amp; 10,000 Views
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/NV8OlJtJuW https://t.co/VizZ1LHeBD
#NarendraModi Sir Demonetization not working in gujarat as people not accepting cards payment.They want cash only # honest At rajkot chotila
Dems waging demonetization WAR on alternative media to bankrupt independent journalism
https://t.co/IP2oAeyrwY
RT @_HazirJawab: Another victim of #Demonetization. Where are @ArvindKejriwal and @OfficeOfRG? https://t.co/iO3a3iYeWB
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Lukewearechange: my news team and I lost the majority of our income through youtube demonetization recently, if you could help plz do
h
Whole country stood in line during #demonetization and you refused to exchange the hard earned money of POOR...so s https://t.co/G5R3lLXqmK
I liked a @YouTube video https://t.co/Z6uje16cez YouTube Demonetization Censorship AdsenseGate: Why TomoNews May Be Forced to Quit
@narendramodi people are  awaiting for demonetization  fruits sir
RT @steve_hanke: ATMs across #India running out of cash once again after withdrawal restrictions were loosened. And Modi still claims #demo
RT @steve_hanke: ATMs across #India running out of cash once again after withdrawal restrictions were loosened. And Modi still claims #demo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
I didn't post any selfies with 2000Rs note after #demonetization ... Will the society accept me? <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+00AD>
#<U+0915><U+094D><U+092F><U+093E>_<U+0938><U+092E><U+093E><U+091C>_<U+0938><U+094D><U+0935><U+0940><U+0915><U+093E><U+0930>_<U+0915><U+0930><U+0947><U+0917><U+093E>
@sonunigam Hahaha.....gundagardi azaan jai....ppl being killed?? Ppl who died in lines during demonetization?? Wo k https://t.co/CriFBJtxle
#Bitcoin Booming in India Due to 'Underlying Benefits' - Not Demonetization #btc https://t.co/AvBbddZdcN
RT @garybcohen: Early Lessons from Indias Demonetization Experiment https://t.co/FUDTcZ10GG #Leadership @harvardbiz
I feel so bad for everyone who has been affected by this demonetization...
Another victim of #Demonetization. Where are @ArvindKejriwal and @OfficeOfRG? https://t.co/iO3a3iYeWB
@RubinReport @ConfessionsExMu did you put muslim or islam anywhere in the name or tag?
that's an auto demonetization.
@PRASHANTHHR @SreenivasanJain How difficult is it to declare Pakistan terror state. Demonetization possible, y not https://t.co/f1uSE0ruzc
RT @WoffordN: YOUTUBE RED ALERT. #Censorship #censored #freespeech #1A #Google $GOOG #pedogate #hillaryclinton #demonetization https://t.co
#AskToModi
Sir,
Ithink if banks raise un justified charges ppl wl favour cash trnxs in turn black money up ?
Demonetization wl be futile ?
8th RT .. @YouTube get it together. <ed><U+00A0><U+00BD><ed><U+00B8><U+00A1> #unfair #unnecessary #demonetization #youtube #youtubetags #youtubers #wtf https://t.co/xgBwInTgDX
India in PANIC MODE as Cash is Running Out! Demonetization Creating Civil Unrest! https://t.co/ZEuPkuv5AA
Income Tax department will investigate over 60k individuals under the second phase of the 'Operation Clean Money'  #demonetization.
Early Lessons from Indias Demonetization Experiment https://t.co/FUDTcZ10GG #Leadership @harvardbiz
RT @d_seaman: @truth_und_love @PrisonPlanet @Cernovich @StefanMolyneux @Lukewearechange @Fulcrum__News @Timcast Then @Timcast has an open i
Uncovering<ed><U+00A0><U+00BD><ed><U+00B9><U+008A> The Truth About YouTube Demonetization AdSense Boycott &amp; Censorship #Censorship #ETNR @morphonios  https://t.co/t6w2hs1ix1
RT @parthology: *Modi didn't check Snapchat accounts during Demonetization*

Intelligentsia : Bad Implementation https://t.co/lxJCKxMbWX
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @WoffordN: YOUTUBE RED ALERT. #Censorship #censored #freespeech #1A #Google $GOOG #pedogate #hillaryclinton #demonetization https://t.co
@narendramodi Hi Modi ji, I think ur feel very hi.
Still we are suffering with Demonetization and we are worry about ur GST.But u said that
YOUTUBE RED ALERT. #Censorship #censored #freespeech #1A #Google $GOOG #pedogate #hillaryclinton #demonetization https://t.co/Khd5v0WzVG
#Demonetization evidence keeps coming in https://t.co/d5IWyMO98S
Modi govt must pay for Demonetization disaster
RT @steve_hanke: ATMs across #India running out of cash once again after withdrawal restrictions were loosened. And Modi still claims #demo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
More people curious about TYT's silence on demonetization story https://t.co/I4TCjs5KpO
@SanjayAzadSln Talks a man who uses derogatory words to describe women &amp; mocks Indians when standing in queue on De https://t.co/nRPjnzIw6z
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Lukewearechange: my news team and I lost the majority of our income through youtube demonetization recently, if you could help plz do
h
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @satishkumarm2: For what??? @RBI ...to make aware how you are torturing the citizenry with your great ideas of demonetization and new ba
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @satishkumarm2: For what??? @RBI ...to make aware how you are torturing the citizenry with your great ideas of demonetization and new ba
#DeMonetization Proved 2 Be Revolutionary Decision 4 #IndiaDefeatsBlackMoney #NewGujarat4NewIndia https://t.co/4Np4mPyqlT
Gujarat has given 100% Support 2 #DeMonetization &amp; #CashlessEconomy #NewGujarat4NewIndia @narendramodi @mygovindia https://t.co/XoepTxeQxQ
@NH_India Lakhs in Karnataka lost their economic stand after demonetization.. recovering with difficulty..
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/XUzzbnDMl8
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/jSOxNZOI8G
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/CjZaz4tMKS
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/clKRd6TgXq
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/LEHxVnXuHa
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/cudzc72QU5
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/N6LgFlBi3w
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/NkC4DkLziN
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/xhIiJwz8zs
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/S3it9Cmj43
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/I6qPA1tRDM
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/6hYAf5yYdx
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/KNQDeVDltk
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/bGL4tFM0sc
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/YIuj3fOwgp
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/AiMl9SJWfA
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/3GDEbWG3TB
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/YmeEF4BKgF
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/9adbr7D5AG
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/IrHhFi39JV
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/DD2WniIPJ6
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/hDJs7lNw3d
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/jlY8XEKMzR
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/l7nDrORf4C
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/CZGdcRjpZJ
The Overall Impact of Demonetization on the Education System in India an article from Motilal Oswal Services https:/ https://t.co/Dn1BUEzNBi
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Unbelievable unity of Developers catering to Primary #RealEstate market welcoming THE changed scenario post https://t.co/Kq15ALHNAv
@VasundharaBJP  at the time of  demonetization, 1 person take away jewellery of rs. 10 lakh, nd now 1/2 @narendramodi  @arjunrammeghwal
RT @OccuWorld: India In PANIC MODE As Cash Is Running Out! Demonetization Creating Civil Unrest! https://t.co/lW3W1HN8Bd
RT @AskAnshul: And, Border Security Force seizes fake notes worth Rs 7,00,000 in Bengal's Malda. You can understand why Mamata was against
<ed><U+00A0><U+00BD><ed><U+00B9><U+008A> The Truth About YouTube Demonetization, AdSense Boycott &amp; Censorship https://t.co/36TgYl7Y7z via @YouTube
India In PANIC MODE As Cash Is Running Out! Demonetization Creating Civil Unrest! https://t.co/lW3W1HN8Bd
How Demonetization Affected Travelers From Around The World https://t.co/dbuSSTfWTo #lifehacks
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @parthavs: Cash no more King-Electronic&amp; #Digital is!!Cash In Use26%Less Than November8 Levels @CFO_India #Demonetization @RBI
https://t
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Super annoying how fellow commoners aren't willing to help with change post #demonetization. Esp. when the auto wala makes faces. #India
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
India in PANIC MODE as Cash is Running Out! Demonetization Creating Civi... https://t.co/SrmEMU4Z9u via @YouTube
RT @DrPippaM: Demonetization: "Out Of Cash" - More Than 90% Of India ATMs Run Dry https://t.co/DY5Jw3X1Vr https://t.co/LcglWWi1aX
Early Lessons from Indias Demonetization Experiment on @harvardbiz https://t.co/mVsygbkzwe https://t.co/AQkVCRrpzP
@AnupVittal prove demonetization right if u hv something
@AnupVittal u r tilting d matter. How can u justify demonetization, explain??????????????????????
That's how people gathered in front of banks &amp; ATM during #demonetization https://t.co/WMx1oWpfZb
Millions wait for hours outside banks as India transitions to new currency notes

Long, snaking lines were seen https://t.co/dTw8nfqJtA
I liked a @YouTube video https://t.co/cjlgLhBaMs <ed><U+00A0><U+00BD><ed><U+00B9><U+008A> The Truth About YouTube Demonetization, AdSense Boycott &amp; Censorship
India Oil Demand Shrinks 3rd Month Amid Demonetization Drag

https://t.co/ysaQyno3dU https://t.co/ZiP6dD8w5q
India in PANIC MODE as Cash is Running Out! Demonetization Creating Civil Unrest! - https://t.co/IIlBxijusN https://t.co/c2zZl1OFFA
@NameFieldmt "India is a poor country and not everyone is literate. One can not force digitization on the public." https://t.co/20WTNr61nQ
@FirstpostBiz Benefits of demonetization <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082>
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @CGDev: Join us tomorrow @ 9:30 for a discussion on #India's econ w/ @arvindsubraman &amp; moderated by @AnnieLowrey https://t.co/blTu78XzQh
Join us tomorrow @ 9:30 for a discussion on #India's econ w/ @arvindsubraman &amp; moderated by @AnnieLowrey https://t.co/blTu78XzQh
I liked a @YouTube video https://t.co/uSCfT2qhui India in PANIC MODE as Cash is Running Out! Demonetization Creating Civil Unrest!
RT @AskAnshul: And, Border Security Force seizes fake notes worth Rs 7,00,000 in Bengal's Malda. You can understand why Mamata was against
RT @analyseasia: Hear @navkendar_IDC offer his perspectives on the #demonetization event in #India &amp; implications to digital payments https
India in PANIC MODE as Cash is Running Out! Demonetization Creating Civi... https://t.co/24G2NiGDkP
RT @steve_hanke: ATMs across #India running out of cash once again after withdrawal restrictions were loosened. And Modi still claims #demo
@PMOIndia Sir demonetization killed 150+ poor Indian within 50 days not a single powerful person got arrested!! Y t https://t.co/5Xaqto3Z2P
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
Increasing economic performance is pointless, if it puts the lives of the poorest at risk.
#demonetization
https://t.co/UoJFkrnjYW
It's 44°C and they won't die,ask them to stand in queue to withdraw cash during demonetization all of a sudden they https://t.co/Sj7o2E80Mp
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Lukewearechange: my news team and I lost the majority of our income through youtube demonetization recently, if you could help plz do
h
RT @DrPippaM: Demonetization: "Out Of Cash" - More Than 90% Of India ATMs Run Dry https://t.co/DY5Jw3X1Vr https://t.co/LcglWWi1aX
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Demonetization, Digital Identity and UBI  How Big Ideas Are Changing India and What it Means for the World https://t.co/GH0JwyicKJ
RT @mkatju: people have got stunts like, Swachata Diwas,Yoga Day, Demonetization,anti-Romeo drives,gau rakshaks,etc.
Yet de have voted for
RT @sundeepgummadi: NDTV reported drop in revenue due to Demonetization ?? <ed><U+00A0><U+00BD><ed><U+00B8><U+00B1><ed><U+00A0><U+00BD><ed><U+00B8><U+00B1> Didn't know they are also in running  Circus... https://t.co/
Hear @navkendar_IDC offer his perspectives on the #demonetization event in #India &amp; implications to digital payments https://t.co/nk92SWh6Ao
RT @DrPippaM: Demonetization: "Out Of Cash" - More Than 90% Of India ATMs Run Dry https://t.co/DY5Jw3X1Vr https://t.co/LcglWWi1aX
RT @sundeepgummadi: NDTV reported drop in revenue due to Demonetization ?? <ed><U+00A0><U+00BD><ed><U+00B8><U+00B1><ed><U+00A0><U+00BD><ed><U+00B8><U+00B1> Didn't know they are also in running  Circus... https://t.co/
RT @steve_hanke: ATMs across #India running out of cash once again after withdrawal restrictions were loosened. And Modi still claims #demo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
NDTV reported drop in revenue due to Demonetization ?? <ed><U+00A0><U+00BD><ed><U+00B8><U+00B1><ed><U+00A0><U+00BD><ed><U+00B8><U+00B1> Didn't know they are also in running  Circus... https://t.co/nqEJbrLGqn
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
India in PANIC MODE as Cash is Running Out! ... - https://t.co/GKxQTXzIxD

#earthsfinal321
#theendishere
#endtimes https://t.co/lL5fXV4Ax8
India in PANIC MODE as Cash is Running Out! Demonetization Creating Civil Unrest! https://t.co/5jP4VNWLtu
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @DrPippaM: Demonetization: "Out Of Cash" - More Than 90% Of India ATMs Run Dry https://t.co/DY5Jw3X1Vr https://t.co/LcglWWi1aX
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
The era post #demonetization in #India:
India's attempt to go cashless is turning food vouchers digital - Mashable https://t.co/Ff91iELpL4
#India's attempt to go #cashless is turning food vouchers digital https://t.co/0aW8Zfnsjh #demonetization
@narendramodi @PMOIndia  applied pancard through UTIITSL 2 mths back.Not got the pan. Saying are issue due to demonetization. Can u help?
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Timcast: Youtube flags my videos for demonetization then after most people have already watched them they will reinstate ads, thus I ge
RT @sidvee: Okay man. Muted trump, clinton, election, demonetization, modi, congress, kejriwal etc. Now how to mute the hate?
RT @URautelaForever: Dear @evanspiegel

RT @AskAnshul: And, Border Security Force seizes fake notes worth Rs 7,00,000 in Bengal's Malda. You can understand why Mamata was against
@RanaAyyub @RazdanNidhi @mediacrooks maybe demonetization had a big effect on their funding in cash
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Stop hating Snapchat's CEO.
Think of d money recovered frm Demonetization &amp; its status.His cmnt ws bad bt v deserve it under PM Modi's rule
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Nr_Shiralkar: India is so rich bc Modi had to do the demonetization to see who actually was poor. <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082> #boycottsnapchat
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
In protest over #YouTube's #AdsenseGate aka #Demonetization and other issues. I've started to #BoycottYouTube once again. #SaveYouTube
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@ndtv @WeThePeopleNDTV @RahulEaswar @RiyaazAmlani #gauraksha #liquorban #beefban #demonetization 1984 2002 https://t.co/1KuXUsy5fa
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @Nr_Shiralkar: India is so rich bc Modi had to do the demonetization to see who actually was poor. <ed><U+00A0><U+00BD><ed><U+00B8><U+0082><ed><U+00A0><U+00BD><ed><U+00B8><U+0082> #boycottsnapchat
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@India_Policy Wat wnet wrong.. loss of AAP? Separatist industry dying down? Demonetization? Stopping of arms lobbyi https://t.co/1eNFzPN8to
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @AskAnshul: And, Border Security Force seizes fake notes worth Rs 7,00,000 in Bengal's Malda. You can understand why Mamata was against
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@SirJadeja people of sadji's delhi gave reply on demonetization by beating Modi's Gujarat https://t.co/X3M4kq7Ce0
Dear #evanspiegal India is so rich that PM #NarendraModi has to implement demonetization to find out  who is actually poor
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @Akshata_M_: @theman_theplan Whether it's a developing/developed country..1 shud 1st learn to respect others<ed><U+00A0><U+00BD><ed><U+00B8><U+0091>India is so rich dat PMModi
@YRDeshmukh Possibly funding drying up post Demonetization ehh. #Demo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Internet got the confidence of all the journalists whose accounts were suddenly getting hacked during demonetization period. bloody frauds
Demonetization Impact was Short-lived: Tata Sponge MD https://t.co/yuVtv2Pwj8
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
#evanspiegel india is so rich that pm narendramodi  had tO implement demonetization to find out is actually poor!
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @BeingHindu: Since post demonetization, none of @RailMinIndia railway stations in Mumbai has mobile payment system. No use of BHIM, Payt
@AAPlogical @kapsology I guess u missed BJP's real estate business ... all those properties bought around demonetiz https://t.co/uz6eBNBwPC
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
Since post demonetization, none of @RailMinIndia railway stations in Mumbai has mobile payment system. No use of BHIM, Paytm, UPI payment.
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@RoflGandhi_ Its was not demonetization its was hekdi of senior player dictatorship of captains.many are victims of https://t.co/PiMtn5FHv9
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@narendramodi presently at surat roadshow. i appreciate your demonetization it is sure that indian rupee will gain its value in three years.
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @manojrammoorthy: No cash in most of the atms from couple of weeks ...
is it another demonetization ?@DemonEtizationn @RBI @canarabanktw
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @aapkarajiv: but v were told that after DeMonetization , militancy was stoped.. Just asking..
@kamaaaa6 @nasirkureshi @Girishaapka @jvsk
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@Onision Demonetization is not the same thing as intolerance. Due to the unreliability of the internet it's likely https://t.co/B3Yl2h29ZC
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
@HumanistReport Congrats! But does this make you a bigger target for YT demonetization program?
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @AskAnshul: And, Border Security Force seizes fake notes worth Rs 7,00,000 in Bengal's Malda. You can understand why Mamata was against
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @AKOUL4774: AKOU future - YouTube Demonetization... https://t.co/THU1OP6tTY
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @RoflGandhi_: Seeing Munaf Patel back after ages <ed><U+00A0><U+00BD><ed><U+00B8><U+008D><ed><U+00A0><U+00BD><ed><U+00B8><U+008D>.. thought we lost him in demonetization. #GLvMI
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually

RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Dear Snapchat.
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poor!#boycottsnapchat
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
@radharaju18 @tufailelif jab se illegal slaughter houses were closed inka dimag bhi bandh hogaya .. Demonetization of a diff kind
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
60,000 only? In a Nation, where less than 2% pay their income tax, &amp; 1% are "declared" crorepatis, how much has #demonetization *cracked*?
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @KyaKaise: 25 viewer Questions about YouTube Demonetization and the latest developments, answered.
25 sawaal YouTube... https://t.co/7b
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@madmanweb @ranjona Demonetization was stupid and every reason given was totally juvenile. This government wants re https://t.co/JvQ1NaHKIx
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Handle Cash With Special Tax Care https://t.co/7TUyFYOXsT #TGI #incometax #blackmoney #demonetization
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Dear @evanspiegel
India is so rich that PM Narendra Modi @narendramodi  had to implement demonetization to find out who is actually poor!
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Demonetization atleast helped someone. https://t.co/DVtdpMlNmx
@krbajithkumar @HKarandikar @myindmakers Demonetization was a huge risk, &amp; BJP could have done it after UP election https://t.co/nLihkxgVWt
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@krbajithkumar @HKarandikar @myindmakers I think most crucial was UP.

And I think demonetization was done with the https://t.co/5wZ5bvhoKM
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@KabirTaneja @gunjakapoor Someone tell me hardly any Kashmir news during UP Poll. Demonetization was suppose to stop all this.
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
#Snapchat
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
@news7tamil @narendramodi @PonnaarrBJP @BJP4TamilNadu @PMOIndia Bank has to be much flexible to the account holders https://t.co/iLtkHtpHZD
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Dear Evan Spiegel Snapchat.
India is so rich that PM Narendra Modi had to implement demonetization to find out... https://t.co/kXzJHlOxvb
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
And WTF means "had to implement demonetization to find out who is actually poor" ??
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poor
@Snapchat
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find https://t.co/3TP2svF
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually
RT @aaanupriyaaa: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually poo
RT @URautelaForever: Dear @evanspiegel
India is so rich that PM Narendra Modi had to implement demonetization to find out who is actually

RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @amazingatheist: It's looking like this demonetization crisis might be coming to an end. *fingers crossed*
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @amazingatheist: It's looking like this demonetization crisis might be coming to an end. *fingers crossed*
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @amazingatheist: It's looking like this demonetization crisis might be coming to an end. *fingers crossed*
It's looking like this demonetization crisis might be coming to an end. *fingers crossed*
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @_YogendraYadav: Good news: Mr RBI Gov can speak!
Did anyone hear him speak on loan waiver for corporates?
Or on demonetization?
https:
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: Demonetization was failure https://t.co/TAEYsN4yBF
@joshenoy Finance Minister doesn't give a damn to these plights. Be it demonetization's implementation failure, or https://t.co/ixM8oEG44h
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
@narendramodi Take a test of temporary full demonetization in #J&amp;K. For three months ban physical currency in Jammu and Kashmir. (1/2)
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
Take a test of temporary full demonetization in #J&amp;K. For three months ban physical currency in Jammu and Kashmir.
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
RT @rahulroushan: By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath
By-polls result today will prove if there's any Modi wave, whether demonetization was successful, whether Yogi Adityanath was right choice.
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
@IncRahamathulla @ShashiTharoor @Inshal07 Gain from demonetization 5400 crore, facial expression of @arunjaitley pr https://t.co/WPETfEAshA
Indian #Silver Imports Fail To Improve Post Demonetization https://t.co/ZlWSy8faXg #podcasts
#Demonetization lingers as #IIP contracts in February https://t.co/3GQD8JKlJ6
#DEMONETIZATION EFFECT ON #REALESTED
https://t.co/FU4g5RNwAm https://t.co/J0QDgAABMU
InRangeTV - YouTube demonetization &amp; Patreon - VLOG - Update 1 https://t.co/Cew2obBhX2
RT @dewindia11: @VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman @khanfah
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
HOW DEMONETIZATION IS A BONANZA FOR INDIAN STARTUP ECOSYSTEM https://t.co/mYQaY75Uwe #StartUp
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
RT @dewindia11: @VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman @khanfah
@puram_politics @sanjayuvacha Rahul Gandhi infact even predicted &amp; cautioned against policy fiasco like demonetizat https://t.co/jPVXmgolyl
RT @analyseasia: Hear @navkendar_IDC describe the rationale why the #India government has decided to proceed with #demonetization https://t
RT @dewindia11: @VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman @khanfah
Hear @navkendar_IDC describe the rationale why the #India government has decided to proceed with #demonetization https://t.co/nk92SWh6Ao
Demonetization lingers as IIP contracts in February.. https://t.co/vOBpVO4dGO
World Bank CEO PM Modis demonetization to stamp out corruption will have positive impact on Indias economy, https://t.co/mYKxukuR8j
Gun channels report YouTube has reduced their ability to run ads. Your USLS channel should be safe, but still...  https://t.co/X0m8m3MnuL
@ArvindKejriwal The top 4 teams in the current IPL are from those places that have non-NDA gvrnmts.This is a verdic https://t.co/crQpxaEAjV
RT @utimutualfund: R. Raja, Head of Products, UTI MF talks about the market post demonetization. Read the excerpts from the Q&amp;A session htt
RT @dewindia11: @VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman @khanfah
RT @dewindia11: @VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman @khanfah
@VPra52 @RaajnathSing @hsr315 @UJ1701 @AAPlogical @JTIn71 @Arv_Ga @Amit_Talwar2 @goeloverseas @rks17353 @1975Raman https://t.co/3xxF5s786n
demonetization had adversely affected rural economy. Healthcare expenditure degrown in rural markets cum Dec https://t.co/MhlF5pisWu
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
RT @GoldTrendsNet: The Fed can do what it wants when it wants
during WWII Hawaiian banknotes were printed
if Japan invaded a demonetization
The latest The Demonetization Daily! https://t.co/grYM1MCBFw Thanks to @jorvieri @michaelsbrooks @Cerebrawl80 #india #aliens
@MotilalOswalLtd Need to b futuristic in this time of demonetization &amp; crisis,so will use my bonus money to invest https://t.co/9P8XYbjUhL
RT @JustinSandefur: Can cash -- or the end of cash -- end poverty in India?
https://t.co/LffZzfOKf8
Feat. @arvindsubraman and @MartinRavall
@timesofindia Let's prez show them mirror of crocodile tears by all these stooges on DeMonetization! Indians now: " https://t.co/FybLxMaHd2
RT @attomeybharti: Headline blames demonetization, report says lack of supply due to staff shortage and year-end closing. <ed><U+00A0><U+00BE><ed><U+00B4><U+00B7><ed><U+00A0><U+00BC><ed><U+00BF><U+00BB><U+200D><U+2642><U+FE0F> https://t.c
THEFIRSTTRILLIONAIRE The Demonetization Effect on India https://t.co/25LLIbmMuk via #sapnajha https://t.co/PHBnxnJXiQ
RT @bitcoinagile: Demonetization Is Catalyzing Digital Payments Growth in India #fintech #payments #mobile https://t.co/MoL0oCLwb2 https://
https://t.co/jAHMTL7yQl Communications Decency Act under the 1st Amend. Section 230 gives immunity from lawsuits 2 Facebook-Twitter-YouTube
The Demonetization Effect on India https://t.co/vBS7X6eUQf #fashion
@rahulkanwal I hope it is not like the Demonetization deaths reported by the media without Doctors certificate or t https://t.co/wov5TIDVpg
RT @geetv79: How Demonetization Helped Govt Formation<U+2753>
The Loot Helped in
MLA Shopping, Subverting Mandates
@KilaFateh @rkhuria @gops333
Demonetization Is Catalyzing Digital Payments Growth in India #fintech #payments #mobile https://t.co/8Cs6BJQCTr https://t.co/2H0Bh8Gtc9
RT @bijonmehta: Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/QNQA1pXE2B #fintech #payments #mobile #digital #
RT @bitcoinagile: Demonetization Is Catalyzing Digital Payments Growth in India #fintech #payments #mobile https://t.co/MoL0oCLwb2 https://
Gun channels report YouTube has reduced their ability to run ads. Your TXLS channel should be safe, but still... https://t.co/qbtbTYbHGY
RT @bijonmehta: Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/QNQA1pXE2B #fintech #payments #mobile #digital #
RT @bitcoinagile: Demonetization Is Catalyzing Digital Payments Growth in India #fintech #payments #mobile https://t.co/MoL0oCLwb2 https://
Demonetization Is Catalyzing Digital Payments Growth in India #fintech #payments #mobile https://t.co/MoL0oCLwb2 https://t.co/9VG9jyhSxU
Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/QNQA1pXE2B #fintech #payments #mobile #digital #india
So youtube decided to say Not eligible for demonetization to all of my videos Didn't make money off my videos but i https://t.co/eNeYVEgRtm
RT @attomeybharti: Headline blames demonetization, report says lack of supply due to staff shortage and year-end closing. <ed><U+00A0><U+00BE><ed><U+00B4><U+00B7><ed><U+00A0><U+00BC><ed><U+00BF><U+00BB><U+200D><U+2642><U+FE0F> https://t.c
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
@Nutnfancy will you address what's going on w/ the demonetization of youtube videos? I know it affects you and many channels. Long live TNP
@d_seaman They are funneling ad revenue back to MSM corporations, it seems fairly obvious, demonetization of small https://t.co/lVMdJXphLl
RT @ms_rana: As per sanghis demonetization was a grand success. So can't be responsible. Must be Modi's pathetic governance then! https://t
RT @getongab: The Demonetization of YouTube is Fast Underway; Dissidents Will Be Silenced | Zero Hedge https://t.co/46R1O1q0CM
Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/T6XjjAHJNe
Demonetization Is Catalyzing Digital Payments Growth in India https://t.co/wVBWZsHJnu #PopulationControl
RT @ms_rana: As per sanghis demonetization was a grand success. So can't be responsible. Must be Modi's pathetic governance then! https://t
RT @ms_rana: As per sanghis demonetization was a grand success. So can't be responsible. Must be Modi's pathetic governance then! https://t
Google News - Mobile Payments: "Demonetization Is Catalyzing Digital Payments Growth in India" https://t.co/K6Cd4ORUJD
RT @jp_koning: During WWII Hawaiian banknotes were printed. If Japan invaded Hawaii, a quick demonetization would render them unusable by o
RT @attomeybharti: Headline blames demonetization, report says lack of supply due to staff shortage and year-end closing. <ed><U+00A0><U+00BE><ed><U+00B4><U+00B7><ed><U+00A0><U+00BC><ed><U+00BF><U+00BB><U+200D><U+2642><U+FE0F> https://t.c
RT @attomeybharti: Headline blames demonetization, report says lack of supply due to staff shortage and year-end closing. <ed><U+00A0><U+00BE><ed><U+00B4><U+00B7><ed><U+00A0><U+00BC><ed><U+00BF><U+00BB><U+200D><U+2642><U+FE0F> https://t.c
RT @GreatGameIndia: Special issue on #DeMonetisation featuring our exclusive research on global #WarOnCash from an Indian perspective https
RT @geetv79: How Demonetization Helped Govt Formation<U+2753>
The Loot Helped in
MLA Shopping, Subverting Mandates
@KilaFateh @rkhuria @gops333
RT @whartonknows: How demonetization could change the face of the Indian economy." https://t.co/TTPmNjeae4
India Oil Demand Shrinks for Third Month Amid Demonetization Drag
India Oil Demand Shrinks for Third Month Amid Demonetization Drag
India Oil Demand Shrinks for Third Month Amid Demonetization Drag - Oil Industry News - Oil and Gas News https://t.co/jU96LV3UOP
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
How Demonetization Affected Travelers From Around The World https://t.co/dbuSSSYluO #lifehacks
RT @rahulroushan: Prohibition is Demonetization 2.0: You kept quiet when poor men's tobacco-gutkha was banned, now they'll love your Englis
RT @GreatGameIndia: Special issue on #DeMonetisation featuring our exclusive research on global #WarOnCash from an Indian perspective https
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
This youtube demonetization is sad, only the people lose. YouTube was a great exchange of ideas.
I liked a @YouTube video https://t.co/1KAJc06TPn Quiting Youtube FIASCO &amp; DEMONETIZATION Ad Boycott EXPLAINED
@ModiLeDubega the size of the economy has been decreased by the value of all unrecovered currency under the event of demonetization scam??
Demonetization Impact was Short-lived: Tata Sponge MD https://t.co/yuVtv2Pwj8
@amazingatheist @YouTube Is the demonetization getting close enough for you to just bail on YouTube completely? Or https://t.co/B6YYP9jqVz
The great YouTube demonetization issue seems to be much less YouTube itself's fault, and much more adverts leaving.
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index) rises to 3.81%
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
RT @attomeybharti: Headline blames demonetization, report says lack of supply due to staff shortage and year-end closing. <ed><U+00A0><U+00BE><ed><U+00B4><U+00B7><ed><U+00A0><U+00BC><ed><U+00BF><U+00BB><U+200D><U+2642><U+FE0F> https://t.c
RT @PiyushGoyalOffc: We believe good economics makes good politics.It's reflected in all our actions, from demonetization to transparent e-
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
Sonu Nigam reaction on demonetization: https://t.co/d1PNax1PWm via @YouTube
RT @GreatGameIndia: .@ashwani_mahajan @s_navroop @WG_Burton @AnkitLal Exclusive research on the global #WarOnCash from an Indian perspectiv
RT @mahcongress: Demonetization Effect : Double Whammy : IIP (Index of Industrial Production) contracts by 1.2% &amp; CPI (Consumer Price Index
.@ashwani_mahajan @s_navroop @WG_Burton @AnkitLal Exclusive research on the global #WarOnCash from an Indian perspe https://t.co/43FUL9VYp2
Yes no reason for BJP to win UP after Demonetization disaster,UP rigging to save Modi,Punjab rigging to protect sta https://t.co/vu76UNzWXu

In [93]:
# extracting only the non-null outputs
mention = []
for i in range(data.shape[0]):
    if data['Prime minister'][i] != []:
        mention.append(data['Prime minister'][i])
mention

[['prime minister sir'],
 ['Prime Minister #'],
 ['Prime minister Sri'],
 ['Prime minister Sri'],
 ['Prime Minister of India'],
 ['Prime Minister @narendramodi']]

In [94]:
# extracting only those sentences which has president's mention
sentences_president = []
for i in range(data.shape[0]):
    if data['Prime minister'][i] != []:
        sentences_president.append(data['text'][i])

In [95]:
sentences_president

['We are with you prime minister sir in fact whole country is with you.jai hind #Demonetization',
 'Open message of #Indian #Child to Prime Minister #Modi\r\n@NarendraModi #Demonetization #Demonetisation https://t.co/Xkf8IJNoUC',
 'RT @urssrilu666: Prime minister Sri @narendramodi hav no idea how common man suffering with cash  no ATMs working outside @RBI big flop of\x85',
 'Prime minister Sri @narendramodi hav no idea how common man suffering with cash  no ATMs working outside @RBI big flop of demonetization',
 'RT @RealHistoryPic: Prime Minister of India showing the list of people  benefited from the demonetization, and Voted "Yes" on his App.(2016\x85',
 'People who criticized #demonetization now\'s the time to say " We apologize to Prime Minister @narendramodi " https://t.co/F9n4Ims9n3']

# Pattern using preposition

In [96]:
# rule 5 function
def rule5(text):

    doc = nlp(text)

    sent = []

    for token in doc:

        # look for prepositions
        if token.pos_=='ADP':

            phrase = ''

            # if its head word is a noun
            if token.head.pos_=='NOUN':

                # append noun and preposition to phrase
                phrase += token.head.text
                phrase += ' '+token.text

                # check the nodes to the right of the preposition
                for right_tok in token.rights:
                    # append if it is a noun or proper noun
                    if (right_tok.pos_ in ['NOUN','PROPN']):
                        phrase += ' '+right_tok.text

                if len(phrase)>2:
                    sent.append(phrase)

    return sent

In [98]:
data = data.drop(columns=['President_Names'])

In [99]:
data.columns

Index(['Unnamed: 0', 'text', 'Prime minister'], dtype='object')

In [101]:
# create a df containing sentence and its output for rule 5
row_list = []

for i in range(len(data)):

    sent = data.loc[i,'text']
    idx = data.loc[i,'Unnamed: 0']

    # rule
    output = rule5(sent)

    dict1 = {'index':idx,'text':sent,'Output':output}
    row_list.append(dict1)

df_rule = pd.DataFrame(row_list)

In [102]:
# first 5 rows
df_rule.head()

,index,text,Output
0,1,RT @rssurjewala: Critical question: Was PayTM ...,[]
1,2,RT @Hemant_80: Did you vote on #Demonetization...,[]
2,3,"RT @roshankar: Former FinSec, RBI Dy Governor,...",[]
3,4,RT @ANI_news: Gurugram (Haryana): Post office ...,[patients in hospitals]
4,5,RT @satishacharya: Reddy Wedding! @mail_today ...,[]

In [103]:
# select non-empty outputs
df_show = pd.DataFrame(columns=df_rule.columns)

for row in range(len(df_rule)):

    if len(df_rule.loc[row,'Output'])!=0:
        df_show = df_show.append(df_rule.loc[row,:])

# reset the index
df_show.reset_index(inplace = True, drop = True)

In [104]:
# first 5 rows
df_show.head()

,index,text,Output
0,4,RT @ANI_news: Gurugram (Haryana): Post office ...,[patients in hospitals]
1,7,RT @gauravcsawant: Rs 40 lakh looted from a ba...,"[bank in Kishtwar, bank in]"
2,8,RT @Joydeep_911: Calling all Nationalists to j...,"[benefits of Demonetization, benefits among mas]"
3,10,National reform now destroyed even the essence...,[essence of sagan]
4,12,RT @Joydas: Question in Narendra Modi App wher...,[Question in App]

In [105]:
# separate noun, preposition and noun

prep_dict = dict()
dis_dict = dict()
dis_list = []

# iterating over all the sentences
for i in range(len(df_show)):

    # sentence containing the output
    sentence = df_show.loc[i,'text']
    # year of the sentence
    year = df_show.loc[i,'index']
    # output of the sentence
    output = df_show.loc[i,'Output']

    # iterating over all the outputs from the sentence
    for sent in output:

        # separate subject, verb and object
        n1, p, n2 = sent.split()[0], sent.split()[1], sent.split()[2:]

        # append to list, along with the sentence
        dis_dict = {'text':sentence,'Year':year,'Noun1':n1,'Preposition':p,'Noun2':n2}
        dis_list.append(dis_dict)

        # counting the number of sentences containing the verb
        prep = sent.split()[1]
        if prep in prep_dict:
            prep_dict[prep]+=1
        else:
            prep_dict[prep]=1

df_sep= pd.DataFrame(dis_list)

In [106]:
df_sep

,text,Year,Noun1,Preposition,Noun2
0,RT @ANI_news: Gurugram (Haryana): Post office ...,4,patients,in,[hospitals]
1,RT @gauravcsawant: Rs 40 lakh looted from a ba...,7,bank,in,[Kishtwar]
2,RT @gauravcsawant: Rs 40 lakh looted from a ba...,7,bank,in,[]
3,RT @Joydeep_911: Calling all Nationalists to j...,8,benefits,of,[Demonetization]
4,RT @Joydeep_911: Calling all Nationalists to j...,8,benefits,among,[mas]
...,...,...,...,...,...
9913,N d modi fans-d true nationalists of the count...,14937,nationalists,of,[stil]
9914,RT @Stupidosaur: @Vidyut B team of BJP. CIA ba...,14939,team,of,[BJP]
9915,RT @Stupidosaur: @Vidyut B team of BJP. CIA ba...,14939,timepass,in,[]
9916,"@Vidyut B team of BJP. CIA baby. CCTV, EVM but...",14940,team,of,[BJP]
9917,"@Vidyut B team of BJP. CIA baby. CCTV, EVM but...",14940,timepass,in,[demon]