---
---

<center><h1>📍 📍 Assignment: Sorting and Aggregating Data 📍 📍</h1></center>

---

#### `READ THE DATASET`

---

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('dataset/time_series.csv')

In [6]:
data.head()

   ID          Datetime  Count
0   0  25-08-2012 00:00      8
1   1  25-08-2012 01:00      2
2   2  25-08-2012 02:00      6
3   3  25-08-2012 03:00      2
4   4  25-08-2012 04:00      2

In [7]:
data.dtypes

ID           int64
Datetime    object
Count        int64
dtype: object

#### `Convert the Datetime column to pandas datetime object`

---

In [8]:
# WRITE YOUR CODE HERE

data.Datetime = pd.to_datetime(data.Datetime)

In [10]:
data.dtypes

ID                   int64
Datetime    datetime64[ns]
Count                int64
dtype: object

---

####  `Create the following features using the Datetime feature`

- day of month
- month
- day of year
- hour

---

In [18]:
# WRITE YOUR CODE HERE
data["day of month"]=data.Datetime.apply(lambda x: x.day_name())
data["moth"]=data.Datetime.apply(lambda x: x.month_name())
data["day of year"]=data.Datetime.apply(lambda x: x.dayofyear)
data["hour"]=data.Datetime.apply(lambda x: x.hour)

In [19]:
data

,ID,Datetime,Count,day of month,moth,day of year,hour
0,0,2012-08-25 00:00:00,8,Saturday,August,238,0
1,1,2012-08-25 01:00:00,2,Saturday,August,238,1
2,2,2012-08-25 02:00:00,6,Saturday,August,238,2
3,3,2012-08-25 03:00:00,2,Saturday,August,238,3
4,4,2012-08-25 04:00:00,2,Saturday,August,238,4
...,...,...,...,...,...,...,...
18283,18283,2014-09-25 19:00:00,868,Thursday,September,268,19
18284,18284,2014-09-25 20:00:00,732,Thursday,September,268,20
18285,18285,2014-09-25 21:00:00,702,Thursday,September,268,21
18286,18286,2014-09-25 22:00:00,580,Thursday,September,268,22
18287,18287,2014-09-25 23:00:00,534,Thursday,September,268,23

---

#### `Consider the following dataframe`

---

In [20]:
sample_df = pd.DataFrame({
    'id'   :  [1, 2, 3, 4, 5],
    'name' :  [ 'Akash', 'Akansha', 'Naman', 'Pulkit', 'Anand'],
    'marks':  [ 22, 23, 43, 41, 12]
})
sample_df

   id     name  marks
0   1    Akash     22
1   2  Akansha     23
2   3    Naman     43
3   4   Pulkit     41
4   5    Anand     12

#### Sort the  dataframe by `marks` column in descending order

---

In [21]:
# WRITE YOUR CODE HERE
sample_df.sort_values(by=['marks'],ascending=False)

   id     name  marks
2   3    Naman     43
3   4   Pulkit     41
1   2  Akansha     23
0   1    Akash     22
4   5    Anand     12

#### Consider another dataframe city
---

In [22]:
city = pd.DataFrame({
    'name' : ['Akash', 'Akansha', 'Pulkit', 'Anand', 'Naman'],
    'city' : ['Delhi', 'Gurugram', 'Gurugram', 'Delhi', 'Noida']
})
city

      name      city
0    Akash     Delhi
1  Akansha  Gurugram
2   Pulkit  Gurugram
3    Anand     Delhi
4    Naman     Noida

***Use the dataframe `sample_df` and `city` and find out the marks of students who live in Gurugram.***

---

In [26]:
### Write your code here
comb_df = sample_df.merge(city,how='right',on="name")
comb_df.loc[comb_df["city"]=="Gurugram"]["marks"]

1    23
2    41
Name: marks, dtype: int64

#### `READ THE BIG MART SALES DATA`

---

In [28]:
big_mart_data = pd.read_csv('dataset/big_mart_sales.csv')

In [29]:
big_mart_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

#### Find out the number of unique `Item_Type` in each of the `Outlet_Identifier`

---

In [30]:
# WRITE YOUR CODE HERE
result = big_mart_data.groupby('Outlet_Identifier')['Item_Type'].nunique().reset_index()
result.columns = ['Outlet_Identifier', 'Unique_Item_Type_Count']

In [31]:
result

  Outlet_Identifier  Unique_Item_Type_Count
0            OUT010                      16
1            OUT013                      16
2            OUT017                      16
3            OUT018                      16
4            OUT019                      16
5            OUT027                      16
6            OUT035                      16
7            OUT045                      16
8            OUT046                      16
9            OUT049                      16

#### Find out the average `Item_Outlet_Sales` for each category of `Outlet_Size`

---

In [32]:
big_mart_data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [34]:
# WRITE YOUR CODE HERE
result = big_mart_data.groupby('Outlet_Size')['Item_Outlet_Sales'].mean().reset_index()
result.columns = ['Outlet_Size', 'Average_Item_Outlet_Sales']

In [36]:
result

  Outlet_Size  Average_Item_Outlet_Sales
0        High                2298.995256
1      Medium                2681.603542
2       Small                1912.149161

#### Select only the categorical variables from the dataframe and use `get_dummies` function to convert those into the numerical ones. 

---

In [37]:
# WRITE YOUR CODE HERE
result = pd.get_dummies(big_mart_data,columns=["Outlet_Size"])

In [38]:
result

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Tier 1,Supermarket Type1,3735.1380,0,1,0
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Tier 3,Supermarket Type2,443.4228,0,1,0
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Tier 1,Supermarket Type1,2097.2700,0,1,0
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Tier 3,Grocery Store,732.3800,0,0,0
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,Tier 3,Supermarket Type1,994.7052,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,Tier 3,Supermarket Type1,2778.3834,1,0,0
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Tier 2,Supermarket Type1,549.2850,0,0,0
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Tier 2,Supermarket Type1,1193.1136,0,0,1
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Tier 3,Supermarket Type2,1845.5976,0,1,0
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Tier 1,Supermarket Type1,765.6700,0,0,1