# Next word recommender

In [1]:
# loading the required libraries
import pandas as pd
import numpy as np
import re
import pickle
import random
from tqdm import tqdm

In [2]:
data = pd.read_csv("sample_reuters_dataset.csv")

In [3]:
data

      sentence_number                                      sentence_text
0                   0  ASIAN EXPORTERS FEAR DAMAGE FROM U . S .- JAPA...
1                   1  They told Reuter correspondents in Asian capit...
2                   2  But some exporters said that while the conflic...
3                   3  The U . S . Has said it will impose 300 mln dl...
4                   4  Unofficial Japanese estimates put the impact o...
...               ...                                                ...
9995             9995  In addition , British Printing and Communicati...
9996             9996  Salomon said in a filing with the Securities a...
9997             9997  If the court decides they should be converted ...
9998             9998  Harcourt is asking the court to rule the compa...
9999             9999  An increase in Reed shares in London today was...

[10000 rows x 2 columns]

In [5]:
# text cleaning
dialogs = data["sentence_text"].tolist()
dialogs_clean = []

for i in dialogs:
  # remove everything except alphabets, ' and white spaces
  i = re.sub("[^a-zA-Z' ]", "", i)
  # convert text to lowercase
  i = i.lower()
  # add cleaned text to the list
  dialogs_clean.append(i)

In [6]:
data["clean_text"] = dialogs_clean

# Creating N-gram, Bi-gram , Tri-gram

In [8]:
# function to create unigrams
# taking a sentence as input
def create_unigram(sentence):
    # creating tokens from the sentence
    tokens = sentence.split()
    # empty list to store the unigrams
    unigram_list = []
    # number of unigrams is equal to the number of tokens in the sentence
    for i in range(len(tokens)):
        # appending each unigram in the list
        unigram_list.append(tokens[i:i+1])
    # returning the unigram list for a sentence    
    return unigram_list

# function to create bigrams
def create_bigram(sentence):
    tokens = sentence.split()
    bigram_list = []
    # number of bigrams is one less than the number of tokens in the sentence
    for i in range(len(tokens)-1):
        bigram_list.append(tokens[i:i+2])
    return bigram_list

# function to create trigrams
def create_trigram(sentence):
    tokens = sentence.split()
    trigram_list = []
    # number of trigrams is two less than the number of tokens in the sentence
    for i in range(len(tokens)-2):
        trigram_list.append(tokens[i:i+3])
    return trigram_list

In [9]:
# creating unigrams for all the sentences in the dataset 
final_unigram = []
# for each sentence
for i in range(data.shape[0]):
    # using the defined unigram function to create unigrams
    final_unigram.append(create_unigram(data['clean_text'][i]))

# adding the unigram in a seperate column in the dataset
data['unigram'] = final_unigram


# creating bigrams for all the sentences in the dataset
final_bigram = []
for i in range(data.shape[0]):
    final_bigram.append(create_bigram(data['clean_text'][i]))

data['bigram'] = final_bigram

# creating trigrams for all the sentences in the dataset
final_trigram = []
for i in range(data.shape[0]):
    final_trigram.append(create_trigram(data['clean_text'][i]))

data['trigram'] = final_trigram

In [10]:
data

,sentence_number,sentence_text,clean_text,unigram,bigram,trigram
0,0,ASIAN EXPORTERS FEAR DAMAGE FROM U . S .- JAPA...,asian exporters fear damage from u s japan r...,"[[asian], [exporters], [fear], [damage], [from...","[[asian, exporters], [exporters, fear], [fear,...","[[asian, exporters, fear], [exporters, fear, d..."
1,1,They told Reuter correspondents in Asian capit...,they told reuter correspondents in asian capit...,"[[they], [told], [reuter], [correspondents], [...","[[they, told], [told, reuter], [reuter, corres...","[[they, told, reuter], [told, reuter, correspo..."
2,2,But some exporters said that while the conflic...,but some exporters said that while the conflic...,"[[but], [some], [exporters], [said], [that], [...","[[but, some], [some, exporters], [exporters, s...","[[but, some, exporters], [some, exporters, sai..."
3,3,The U . S . Has said it will impose 300 mln dl...,the u s has said it will impose mln dlrs of...,"[[the], [u], [s], [has], [said], [it], [will],...","[[the, u], [u, s], [s, has], [has, said], [sai...","[[the, u, s], [u, s, has], [s, has, said], [ha..."
4,4,Unofficial Japanese estimates put the impact o...,unofficial japanese estimates put the impact o...,"[[unofficial], [japanese], [estimates], [put],...","[[unofficial, japanese], [japanese, estimates]...","[[unofficial, japanese, estimates], [japanese,..."
...,...,...,...,...,...,...
9995,9995,"In addition , British Printing and Communicati...",in addition british printing and communicatio...,"[[in], [addition], [british], [printing], [and...","[[in, addition], [addition, british], [british...","[[in, addition, british], [addition, british, ..."
9996,9996,Salomon said in a filing with the Securities a...,salomon said in a filing with the securities a...,"[[salomon], [said], [in], [a], [filing], [with...","[[salomon, said], [said, in], [in, a], [a, fil...","[[salomon, said, in], [said, in, a], [in, a, f..."
9997,9997,If the court decides they should be converted ...,if the court decides they should be converted ...,"[[if], [the], [court], [decides], [they], [sho...","[[if, the], [the, court], [court, decides], [d...","[[if, the, court], [the, court, decides], [cou..."
9998,9998,Harcourt is asking the court to rule the compa...,harcourt is asking the court to rule the compa...,"[[harcourt], [is], [asking], [the], [court], [...","[[harcourt, is], [is, asking], [asking, the], ...","[[harcourt, is, asking], [is, asking, the], [a..."
9999,9999,An increase in Reed shares in London today was...,an increase in reed shares in london today was...,"[[an], [increase], [in], [reed], [shares], [in...","[[an, increase], [increase, in], [in, reed], [...","[[an, increase, in], [increase, in, reed], [in..."

# Build N-gram language model

In [12]:
# for defining the N-gram model
from collections import Counter, defaultdict

# Create a placeholder for model
model = defaultdict(lambda: defaultdict(lambda: 0))

# Count frequency of co-occurance  
for i in range(data.shape[0]):
    # for each trigram pair
    for w1, w2, w3 in create_trigram(data['clean_text'][i]):
        # count the occurance of word 3, given word 1 and word 2
        model[(w1, w2)][w3] += 1

In [13]:
model

defaultdict(<function __main__.<lambda>()>,
            {('asian',
              'exporters'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'fear': 1}),
             ('exporters',
              'fear'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'damage': 1}),
             ('fear',
              'damage'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'from': 1}),
             ('damage',
              'from'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'u': 1,
                          'local': 1}),
             ('from',
              'u'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'s': 5,
                          'k': 1}),
             ('u',
              's'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'japan': 6,
                          'and': 34,
                          'move': 1,
                          'has': 7,
                          'said': 4,
                          'products': 5,
                          'up': 2,
                          'pressure': 3,
                          'last': 5,
                          'exports': 8,
                          'japanese': 5,
                          'trade': 44,
                          'department': 3,
                          'dlrs': 36,
                          'securities': 2,
                          'glass': 1,
                          'commercial': 1,
                          'officials': 30,
                          'farm': 6,
                          'would': 5,
                          'to': 6,
                          'he': 4,
                          'agriculture': 72,
                          'market': 7,
                          'corn': 12,
                          'will': 2,
                          'feedgrain': 1,
                          'which': 2,
                          'limit': 1,
                          'based': 2,
                          'currency': 13,
                          'sanctions': 3,
                          'official': 3,
                          'not': 3,
                          'hopes': 2,
                          'investors': 1,
                          'dollar': 24,
                          'unit': 3,
                          'where': 6,
                          'charges': 1,
                          'decision': 1,
                          'chip': 2,
                          'concern': 1,
                          'complaint': 1,
                          'banking': 4,
                          'treasury': 10,
                          'petrochemical': 2,
                          'chemical': 3,
                          'economy': 12,
                          'dlr': 9,
                          'textile': 6,
                          'investor': 1,
                          'defense': 4,
                          'government': 11,
                          'no': 2,
                          'a': 6,
                          'parent': 1,
                          'acquisition': 1,
                          'tariffs': 4,
                          'semiconductor': 3,
                          'firms': 4,
                          'purchase': 1,
                          'medical': 2,
                          'subsidiary': 6,
                          'loan': 1,
                          'lawmakers': 2,
                          'dairy': 1,
                          'interest': 8,
                          'engineering': 1,
                          'reserves': 1,
                          'producers': 3,
                          'meat': 9,
                          'broilers': 1,
                          'wheat': 8,
                          'ports': 2,
                          'prices': 1,
                          'economic': 3,
                          'probably': 1,
                          'over': 2,
                          'steel': 2,
                          'have': 1,
                          'senate': 5,
                          'oil': 11,
                          'consumption': 1,
                          'current': 3,
                          'imports': 2,
                          'at': 2,
                          'that': 1,
                          'output': 1,
                          'february': 4,
                          'aegon': 1,
                          'insurer': 1,
                          'thus': 1,
                          'first': 2,
                          'funds': 2,
                          'energy': 4,
                          'gulf': 4,
                          'commitment': 2,
                          'company': 4,
                          'buying': 1,
                          'lead': 2,
                          'courier': 2,
                          'traders': 2,
                          'congress': 3,
                          'remained': 1,
                          'tobacco': 1,
                          'italy': 1,
                          'march': 1,
                          'retailers': 1,
                          'soyoil': 1,
                          'sugar': 2,
                          'cts': 2,
                          'outlook': 1,
                          'ending': 2,
                          'orange': 3,
                          'supply': 4,
                          'citrus': 1,
                          'ussr': 3,
                          'e': 1,
                          'exporters': 2,
                          'bankruptcy': 4,
                          'may': 1,
                          'depended': 1,
                          'than': 1,
                          'dependency': 1,
                          'hatching': 1,
                          'protein': 1,
                          'weekly': 1,
                          'soybean': 1,
                          'x': 1,
                          'quality': 1,
                          'producing': 1,
                          'spot': 1,
                          'm': 4,
                          'discount': 3,
                          'bank': 4,
                          'money': 3,
                          'crude': 2,
                          'relected': 1,
                          'west': 2,
                          'federal': 3,
                          'commodities': 1,
                          'markets': 1,
                          'financial': 2,
                          'reflected': 1,
                          'budget': 4,
                          'is': 3,
                          'hurting': 1,
                          'calls': 3,
                          'machinery': 2,
                          'green': 1,
                          'roastings': 1,
                          'european': 1,
                          'u': 1,
                          'bond': 1,
                          'richards': 1,
                          'companies': 2,
                          'rate': 1,
                          'monetary': 4,
                          'industry': 3,
                          'mln': 1,
                          'feeder': 2,
                          'bancorp': 5,
                          'employees': 1,
                          'trust': 6,
                          'by': 2,
                          'underwriters': 1,
                          'revenues': 1,
                          'it': 1,
                          'on': 5,
                          'sets': 1,
                          'sprint': 1,
                          'gas': 1,
                          'competitors': 1,
                          'plants': 3,
                          'cattle': 2,
                          'banks': 3,
                          'inflation': 1,
                          'east': 1,
                          'rice': 2,
                          'agricultural': 3,
                          'agency': 1,
                          'international': 1,
                          'customs': 1,
                          'bankrupcty': 1,
                          'supreme': 1,
                          'bid': 1,
                          'believed': 1,
                          'bill': 1,
                          'soybeans': 5,
                          'commerce': 4,
                          'urges': 2,
                          'they': 2,
                          'rose': 3,
                          'the': 2,
                          'proposal': 1,
                          'foodgrains': 1,
                          'reprisals': 1,
                          'goods': 3,
                          'china': 1,
                          'rules': 1,
                          'support': 1,
                          'retaliation': 1,
                          'central': 1,
                          'business': 1,
                          'trading': 2,
                          'arm': 1,
                          'gnp': 1,
                          'south': 2,
                          'had': 2,
                          'study': 1,
                          'consumer': 3,
                          'industrial': 1,
                          'industries': 1,
                          'manufacturing': 1,
                          'district': 6,
                          'rig': 1,
                          'drilling': 1,
                          'countervailing': 1,
                          'or': 1,
                          'zimmerman': 1,
                          'forest': 1,
                          'system': 1,
                          'in': 2,
                          'lumbermen': 1,
                          'lumber': 1,
                          'justice': 1,
                          'publishing': 1,
                          'video': 4,
                          'allies': 2,
                          'frigate': 3,
                          'thrift': 3,
                          'unprepared': 1,
                          'participation': 1,
                          'military': 4,
                          'action': 1,
                          'court': 4,
                          'be': 1,
                          'hart': 1,
                          'did': 1,
                          'firm': 2,
                          'sectors': 1,
                          'investment': 1,
                          'should': 1,
                          'gold': 2,
                          'salmonellosis': 1,
                          'house': 7,
                          'allegis': 1,
                          'weighs': 1,
                          'domestic': 1,
                          "'": 1,
                          'analysts': 1,
                          'stocks': 2,
                          'secretary': 2,
                          'might': 1,
                          'could': 2,
                          'feed': 1,
                          'flag': 3,
                          'arms': 2,
                          'warships': 3,
                          'inc': 1,
                          'holding': 1,
                          'barley': 2,
                          'flags': 2,
                          'forces': 1,
                          'wood': 1,
                          'april': 1,
                          'production': 1,
                          'reserve': 3,
                          'policy': 2,
                          'upgraded': 1,
                          'britain': 1,
                          'owned': 1,
                          'copper': 1,
                          'warship': 1,
                          'plan': 1,
                          'during': 1,
                          'beef': 4,
                          'tenderloin': 1,
                          'striploin': 1,
                          'into': 1,
                          'deficit': 2,
                          'health': 1,
                          'personal': 1,
                          'league': 1,
                          'benchmark': 1,
                          'for': 2,
                          'cent': 1,
                          'superfund': 1,
                          'was': 1,
                          'chamber': 1,
                          'technology': 1,
                          'growth': 1,
                          'farmers': 1,
                          'canada': 1,
                          'canadian': 1,
                          'put': 1,
                          'combining': 1,
                          'housing': 1,
                          'you': 1,
                          'shaw': 1,
                          'failed': 1,
                          'groundnut': 1}),
             ('s',
              'japan'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'rift': 1,
                          "'": 2,
                          'west': 2,
                          'trade': 1}),
             ('japan',
              'rift'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'mounting': 1}),
             ('rift',
              'mounting'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'trade': 1}),
             ('mounting',
              'trade'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'friction': 1,
                          'tension': 1}),
             ('trade',
              'friction'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'between': 3,
                          'with': 1,
                          'diplomacy': 1,
                          'and': 1}),
             ('friction',
              'between'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'the': 3}),
             ('between',
              'the'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'u': 5,
                          'start': 1,
                          'two': 18,
                          'employers': 1,
                          'united': 4,
                          'demands': 1,
                          'countries': 1,
                          'ec': 1,
                          'dollar': 1,
                          'white': 1,
                          'prime': 3,
                          'report': 2,
                          'increased': 1,
                          'secured': 1,
                          'pork': 1,
                          'omani': 1,
                          'group': 1,
                          'purchase': 1,
                          'federal': 1,
                          'first': 1,
                          'heaviest': 1,
                          'growth': 1}),
             ('the',
              'u'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'s': 413,
                          'k': 17,
                          'n': 1}),
             ('s',
              'and'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'japan': 6,
                          'lead': 1,
                          'atlas': 1,
                          'new': 1,
                          'japanese': 3,
                          'rising': 1,
                          'britain': 2,
                          'europe': 2,
                          'west': 3,
                          'world': 1,
                          'european': 1,
                          'the': 2,
                          'cain': 1,
                          'canada': 2,
                          'l': 1,
                          'up': 1,
                          'hong': 1,
                          'u': 1,
                          'its': 1,
                          'w': 4,
                          'other': 2,
                          'malaysia': 1,
                          'rupert': 1,
                          'tight': 1,
                          'on': 1,
                          'canadian': 1,
                          'raise': 1}),
             ('and',
              'japan'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'has': 1,
                          'might': 1,
                          'with': 2,
                          "'": 2,
                          'harder': 1,
                          'look': 1,
                          'on': 3,
                          'believe': 1,
                          'became': 1,
                          'which': 1,
                          'meanwhile': 1,
                          'rather': 1,
                          'will': 2,
                          'at': 1,
                          'to': 2}),
             ('japan',
              'has'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'raised': 1,
                          'been': 2,
                          'the': 1,
                          'little': 2,
                          'violated': 1,
                          'said': 3,
                          'come': 1,
                          'no': 3,
                          'rejected': 1,
                          'far': 1,
                          'resulted': 1}),
             ('has',
              'raised'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'fears': 1,
                          'its': 2,
                          'concern': 1,
                          'the': 1,
                          'his': 1,
                          'prices': 1}),
             ('raised',
              'fears'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'among': 1}),
             ('fears',
              'among'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'many': 1}),
             ('among',
              'many'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'of': 1}),
             ('many',
              'of'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'asia': 1,
                          'the': 3}),
             ('of',
              'asia'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {"'": 1}),
             ('asia',
              "'"): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'s': 1}),
             ("'",
              's'): defaultdict(<function __main__.<lambda>.<locals>.<lambda>()>, {'exporting': 1,
                          'loss': 1,
                          'alleged': 3,
                          'foreign': 20,
                          'largest': 23,
                          'trade': 23,
                          'biggest': 7,
                          'concerns': 1,
                          'two': 4,
                          'ruling': 6,
                          'avowed': 1,
                          'deputy': 1,
                          'grain': 4,
                          'fruit': 1,
                          'electric': 1,
                          'improved': 1,
                          'oil': 12,
                          'second': 6,
                          'workers': 2,
                          'elections': 1,
                          'most': 6,
                          'profitability': 1,
                          'branch': 1,
                          'large': 1,
                          'largely': 1,
                          'problems': 2,
                          'version': 1,
                          'the': 5,
                          'sumitomo': 1,
                          'smithson': 1,
                          'a': 13,
                          'tender': 5,
                          'allocation': 1,
                          'existing': 2,
                          'gold': 5,
                          'life': 3,
                          'industrial': 4,
                          'daily': 2,
                          'agriculture': 1,
                          'top': 5,
                          'exports': 2,
                          'current': 25,
                          'gnp': 3,

In [17]:
dict(model['that','the'])

{'row': 1,
 'exchange': 1,
 'withdrawal': 1,
 'underlying': 2,
 'two': 3,
 'situation': 4,
 'listings': 1,
 'issuing': 1,
 'process': 1,
 'transaction': 1,
 'dollar': 13,
 'correction': 1,
 'mark': 2,
 'u': 10,
 'chemical': 1,
 'cocoa': 1,
 'storage': 1,
 'parties': 1,
 'company': 11,
 'italian': 1,
 'danger': 1,
 'talks': 2,
 'first': 1,
 'move': 2,
 'market': 2,
 'negotiation': 1,
 'value': 1,
 'only': 2,
 'discount': 1,
 'bundesbank': 2,
 'commission': 1,
 'current': 4,
 'solidarity': 1,
 'markets': 4,
 'changes': 1,
 'key': 2,
 'average': 2,
 'last': 1,
 'ability': 1,
 'impact': 1,
 'total': 1,
 'german': 1,
 'substantial': 1,
 'reagan': 2,
 'bill': 1,
 'financial': 2,
 'finance': 1,
 'full': 1,
 'it': 1,
 'consumer': 1,
 'government': 8,
 'monthly': 1,
 'so': 1,
 'soviet': 2,
 'fire': 1,
 'securing': 1,
 'second': 2,
 'system': 2,
 'fund': 1,
 'industrial': 1,
 'fed': 19,
 'latest': 1,
 'yen': 2,
 'controlled': 1,
 'foreign': 1,
 'tariffs': 2,
 'group': 2,
 'much': 1,
 'worst': 1,
 'debtholders': 2,
 'ec': 4,
 'bankers': 1,
 'highest': 1,
 'grind': 1,
 'estimates': 1,
 'braking': 1,
 'trade': 2,
 'strengthening': 1,
 'positive': 1,
 'scope': 1,
 'americans': 1,
 'amended': 1,
 'mln': 1,
 'companies': 1,
 'issue': 1,
 'price': 3,
 'other': 1,
 'plants': 1,
 'chances': 1,
 'energy': 1,
 'epa': 1,
 'imports': 1,
 'removal': 2,
 'central': 2,
 'japanese': 2,
 'sale': 1,
 'federal': 3,
 'commerce': 1,
 'pct': 1,
 'health': 1,
 'main': 2,
 'trading': 2,
 'standard': 1,
 'bank': 2,
 'factor': 1,
 'philippines': 1,
 'pact': 2,
 'offer': 1,
 'renegotiations': 1,
 'dutch': 1,
 'merger': 1,
 'deal': 1,
 'elimination': 1,
 'allies': 1,
 'management': 1,
 'pipeline': 3,
 'water': 1,
 'proposed': 1,
 'shareholding': 1,
 'independent': 1,
 'net': 1,
 'west': 3,
 'economy': 6,
 'petroleum': 1,
 'peso': 1,
 'united': 1,
 'area': 1,
 'vessels': 1,
 'measure': 1,
 'rising': 1,
 'remaining': 2,
 'downtrend': 1,
 'louvre': 1,
 'six': 1,
 'white': 1,
 'intent': 1,
 'budget': 2,
 'acp': 1,
 'british': 1,
 'timing': 1,
 'proposal': 1,
 'the': 1,
 'telegraph': 1,
 'country': 1,
 'status': 1,
 'shares': 1,
 'returns': 1,
 'share': 1,
 'merged': 1,
 'crop': 1,
 'document': 1,
 'ruling': 1,
 'acquisition': 1,
 'sacrifices': 1,
 'provisions': 1,
 'auction': 1,
 'storm': 1,
 'purchasing': 1,
 'metal': 2,
 'medium': 1,
 'gnp': 1,
 'ministry': 1,
 'dlrs': 1}